---
exclude: '^.*\.svg$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # - id: check-executables-have-shebangs
      - id: check-merge-conflict
      # - id: check-docstring-first # We can enable this rule once models.py is simplified
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        exclude: ^api/resources_portal/wsgi.py$

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        additional_dependancies:
          - eslint@^6.8.0
          - eslint-config-airbnb@18.1.0
          - eslint-config-prettier@^6.10.1
          - eslint-plugin-import@^2.20.2
          - eslint-plugin-jsx-a11y@^6.2.3
          - eslint-plugin-react@^7.19.0
          - eslint-plugin-react-hooks@^2.5.1
