site_name: resources-portal
site_description: Resources Portal
repo_url: https://github.com/ccdl/resources-portal
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/ccdl">ccdl</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
