# Generated by Django 3.0.3 on 2020-03-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("resources_portal", "0003_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"db_table": "organizations", "get_latest_by": "created_at",},
        ),
        migrations.RenameField(
            model_name="material", old_name="metadata", new_name="additional_metadata",
        ),
        migrations.RenameField(
            model_name="material", old_name="primary_contact", new_name="contact_user",
        ),
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material",
            name="mta",
            field=models.CharField(
                blank=True,
                help_text="Contains an url to download the MTA.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="material", name="needs_irb", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material", name="needs_mta", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="material",
            name="url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
                ("assigned_only", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "user_notifications", "get_latest_by": "created_at",},
        ),
        migrations.CreateModel(
            name="OrganizationUserPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="resources_portal.Organization",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.Permission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"db_table": "organization_user_permission", "get_latest_by": "created_at",},
        ),
        migrations.CreateModel(
            name="MaterialShareEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.DateTimeField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_share_assigned_to_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_events",
                        to="resources_portal.Material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_share_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "material_share_events", "get_latest_by": "created_at",},
        ),
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mta", models.CharField(blank=True, max_length=255, null=True)),
                ("irb", models.CharField(blank=True, max_length=255, null=True)),
                ("executed_mta", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="resources_portal.Material",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "material_requests", "get_latest_by": "created_at",},
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("founder_id", models.CharField(max_length=80)),
                (
                    "materials",
                    models.ManyToManyField(related_name="grants", to="resources_portal.Material"),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        related_name="grants", to="resources_portal.Organization"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(related_name="grants", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"db_table": "grants", "get_latest_by": "created_at",},
        ),
        migrations.AddField(
            model_name="material",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="resources_portal.Organization",
            ),
            preserve_default=False,
        ),
    ]
