from resources_portal.views.material import MaterialDocumentView, MaterialViewSet
from resources_portal.views.organization import OrganizationDocumentView
from resources_portal.views.user import UserCreateViewSet, UserDocumentView, UserViewSet
