// attribute name to markdown string
export const helperTexts = {
  abstract: undefined,
  accession_code: undefined,
  age: undefined,
  backbone_name: undefined,
  bacterial_resistance: undefined,
  bio_safety_leve: undefined,
  bio_safety_level: undefined,
  cell_line_name: undefined,
  citation: `How do you want researchers to cite this resource?`,
  cloning_method: undefined,
  consent_to_share: undefined,
  construct_details: undefined,
  contact_user: `This person is responsible for responding to inquiries about resource details, shipping and handling, etc.`,
  copy_number: undefined,
  cryopreservation: undefined,
  culture_condition: undefined,
  description: undefined,
  diagnosis: undefined,
  disease: undefined,
  disease_stage: undefined,
  engraftment_rate: undefined,
  engraftment_tim: undefined,
  ethnicity: undefined,
  existing_model_explanatio: undefined,
  gender: undefined,
  gene_insert_name: undefined,
  genetic_background: undefined,
  governance_restriction: undefined,
  growth_medium: undefined,
  growth_strain: undefined,
  growth_temp_celsius: undefined,
  histology: undefined,
  injection_type_and_site: undefined,
  is_from_untreated_patient: undefined,
  is_not_of_EBV_origin: undefined,
  is_passage_QA_performed: undefined,
  is_strain_immunized: undefined,
  lag_time: undefined,
  matastases_in_strain: undefined,
  model_organism: undefined,
  model_strain_and_source: undefined,
  number_of_available_models: undefined,
  number_of_available_samples: undefined,
  number_of_availible_cell_lines: undefined,
  number_of_availible_models: undefined,
  number_of_samples: undefined,
  organisms: `Provide scientific names of organisms`,
  patient_id: undefined,
  pdx_id: undefined,
  pdx_model_availability: undefined,
  plasmid_name: undefined,
  plasmid_type: undefined,
  platform: undefined,
  population_doubling_time: undefined,
  pre_print_doi: `Example: [bioRxiv](http://link) DOI`,
  primary_vector_type: undefined,
  prior_treatment_protocol: undefined,
  protocol_name: undefined,
  purpose: `What does this plasmid do?`,
  relevant_mutations: `Mention any mutations in the gene/insert`,
  response_to_QA_performed: undefined,
  response_to_standard_of_car: undefined,
  response_to_treatment: undefined,
  sex: undefined,
  sequence_maps: `Upload the full sequence and partial sequence maps. You can generate sequence maps [here](http://link).`,
  specific_markers: undefined,
  specimen_tumor_tissue: undefined,
  storage_medium: undefined,
  str_profile: `You obtain an STR profile for your cell line [here](http://link).`,
  subculturing: undefined,
  submitter_tumor_id: undefined,
  technology: undefined,
  tissue: undefined,
  tissue_of_origin: undefined,
  treatment_drug: undefined,
  treatment_for_engraftment: undefined,
  treatment_passage: undefined,
  treatment_protocol: undefined,
  treatment_response: undefined,
  tumor_chracterization_technology: undefined,
  tumor_grade: undefined,
  tumor_omics: undefined,
  tumor_preparation: undefined,
  tumor_sample_type: undefined,
  tumor_type: undefined,
  type_of_humanization: undefined,
  virology_status: undefined,
  zygosity: undefined
}

export default (attribute) => {
  return helperTexts[attribute]
}
