export const knownOrganisms = [
  'Ciona Intestinalis',
  'Taeniopygia Guttata',
  'Petromyzon Marinus',
  'Anas Platyrhynchos',
  'Ciona Savignyi',
  'Ficedula Albicollis',
  'Tetraodon Nigroviridis',
  'Astyanax Mexicanus',
  'Gadus Morhua',
  'Oryzias Latipes',
  'Gasterosteus Aculeatus',
  'Pelodiscus Sinensis',
  'Cricetulus Griseus Chok1gshd',
  'Xiphophorus Maculatus',
  'Cavia Aperea',
  'Erinaceus Europaeus',
  'Pteropus Vampyrus',
  'Xenopus Tropicalis',
  'Otolemur Garnettii',
  'Takifugu Rubripes',
  'Choloepus Hoffmanni',
  'Meleagris Gallopavo',
  'Ochotona Princeps',
  'Lepisosteus Oculatus',
  'Myotis Lucifugus',
  'Gorilla',
  'Ailuropoda Melanoleuca',
  'Lemur Catta',
  'Tursiops Truncatus',
  'Peromyscus Maniculatus Bairdii',
  'Anolis Carolinensis',
  'Vicugna Pacos',
  'Chlorocebus Sabaeus',
  'Eptatretus Burgeri',
  'Sorex Araneus',
  'Colobus Angolensis Palliatus',
  'Cavia Porcellus',
  'Canis Familiaris',
  'Capra Hircus',
  'Monodelphis Domestica',
  'Oreochromis Niloticus',
  'Echinops Telfairi',
  'Panthera Tigris Altaica',
  'Poecilia Formosa',
  'Latimeria Chalumnae',
  'Rana Catesbeiana',
  'Ictidomys Tridecemlineatus',
  'Mus',
  'Branchiostoma Floridae',
  'Strongylocentrotus Purpuratus',
  'Oryctolagus Cuniculus',
  'Chinchilla Lanigera',
  'Procavia Capensis',
  'Felis Catus',
  'Notamacropus Eugenii',
  'Mus Pahari',
  'Pukia Falcata',
  'Callithrix Jacchus',
  'Ambystoma Mexicanum',
  'Apis Mellifera',
  'Unidentified',
  'Pleurobrachia Sp. Uf-2017',
  'Mus Musculus Domesticus',
  'Microcebus Murinus',
  'Coeloplana Meteoris',
  'Saccharomyces Pastorianus',
  'Pseudomonas Putida',
  'Tupaia Belangeri',
  'Loxodonta Africana',
  'Leymus Triticoides',
  'Solanum Pimpinellifolium',
  'Cebus Capucinus',
  'Sarcophilus Harrisii',
  'Microtus Ochrogaster',
  'Callianira Antarctica',
  'Pongo Abelii',
  'Dasypus Novemcinctus',
  'Macaca Nemestrina',
  'Procapra Przewalskii',
  'Triticum Turgidum Subsp. Durum',
  'Microtus Pennsylvanicus',
  'Mus Musculus Musculus X M. M. Castaneus',
  'Papio Anubis',
  'Trypanosoma Cruzi',
  'Xenopus Muelleri',
  'Mus Spretus',
  'Mycobacterium Tuberculosis H37rv',
  'Hemaris Diffinis',
  'Mycobacterium Bovis Bcg Str. Atcc 35733',
  'Heterocephalus Glaber',
  'Mustela Putorius Furo',
  'Rattus Norvegicus',
  'Arabidopsis Thaliana',
  'Musculus',
  'Pan Troglodytes',
  'Marmota Monax',
  'Mus Musculus X Mus Spretus',
  'Citrus Maxima',
  'Neovison Vison',
  'Staphylococcus Aureus Subsp. Aureus Rn4220',
  'Staphylococcus Aureus Subsp. Aureus Usa300',
  'Boechera Gunnisoniana',
  'Manihot Esculenta',
  'Beroe Sp. Uf-2017',
  'Saccharomyces Cerevisiae Vin13',
  'Mus Musculus Musculus',
  'Chlorocebus Aethiops Vervet',
  'Lobatolampea Tetragona',
  'Populus Balsamifera',
  'Heterodera Glycines',
  'Mixed Sample',
  'Bacillus Subtilis Subsp. Subtilis Str. 168',
  'Arabidopsis Thaliana X Arabidopsis Halleri Subsp. Gemmifera',
  'Bifidobacterium Longum',
  'Populus Tremula',
  'Populus Tremula X Populus Tremuloides',
  'Populus Tomentosa',
  'Theobroma Cacao',
  'Escherichia Coli 8624',
  'Escherichia Coli Sci-07',
  'Escherichia Coli Bw25113',
  'Escherichia Coli Cft073',
  'Escherichia Coli Apec O2',
  'Aptenodytes Patagonicus',
  'Coturnix Japonica',
  'Escherichia Coli O08',
  'Macaca Radiata',
  'Vigna Unguiculata',
  'Phytophthora Sojae',
  'Phaseolus Coccineus',
  'Gossypium Trilobum',
  'Fukomys Mechowii',
  'Peromyscus Californicus',
  'Mixed Libraries',
  'Propithecus Coquereli',
  'Nicotiana Tabacum',
  'Vulpes Vulpes',
  'Eulemur Mongoz',
  'Cuscuta Pentagona',
  'Galago Senegalensis',
  'Phascolarctos Cinereus',
  'Drosophila Mauritiana',
  'Drosophila Teissieri',
  'Gossypium Arboreum',
  'Rorippa Sylvestris',
  'Triticum Carthlicum',
  'Brassica Oleracea',
  'Escherichia Coli Str. K-12 Substr. Dh10b',
  'Peromyscus Maniculatus',
  'Prunella Modularis',
  'Rhizopus Oryzae',
  'Yersinia Pseudotuberculosis Ip 32953',
  'Pasteurella Multocida',
  'Veillonella Parvula Dsm 2008',
  'Streptococcus Sp. Cect 9732',
  'Homo',
  'Crocodylus Porosus',
  'Strongyloides Ratti',
  'Drosophila Persimilis',
  'Helobdella Robusta',
  'Drosophila Erecta',
  'Teleopsis Dalmanni',
  'Nematostella Vectensis',
  'Lingula Anatina',
  'Amphimedon Queenslandica',
  'Ixodes Scapularis',
  'Acyrthosiphon Pisum',
  'Xiphophorus Couchianus',
  'Lepidothrix Coronata',
  'Mastacembelus Armatus',
  'Scophthalmus Maximus',
  'Bdelloura Candida',
  'Talaromyces Borbonicus',
  'Astatotilapia Calliptera',
  'Chelonoidis Abingdonii',
  'Nothoprocta Perdicaria',
  'Anser Brachyrhynchus',
  'Salvator Merianae',
  'Amphiprion Ocellaris',
  'Apteryx Haastii',
  'Maylandia Zebra',
  'Parus Major',
  'Vitis Riparia',
  'Staphylococcus Aureus',
  'Gossypium Hirsutum',
  'Escherichia Coli',
  'Sus Scrofa',
  'Peromyscus Polionotus',
  'Mus Sp.',
  'Haemophilus Influenzae',
  'Cervus Elaphus',
  'Mus Caroli',
  'Festuca Rubra Subsp. Fallax',
  'Mus Musculus Castaneus',
  'Plasmodium Chabaudi',
  'Alopecurus Myosuroides',
  'Arabidopsis Halleri Subsp. Gemmifera',
  'Rana Pirica',
  'Vitis Aestivalis',
  'Actias Luna',
  'Plasmodium Berghei',
  'Ornithorhynchus Anatinus',
  'Eidolon Helvum',
  'Vitis Cinerea Var. Helleri X Vitis Vinifera',
  'Vitis Cinerea Var. Helleri X Vitis Rupestris',
  'Vitis Cinerea Var. Helleri X Vitis Riparia',
  'Avena Sativa',
  'Populus Simonii',
  'Saccharomyces Pastorianus Weihenstephan 34/70',
  'Saccharomyces Cerevisiae Ec1118',
  'Carica Papaya',
  'Arabidopsis Lyrata Subsp. Petraea',
  'Saccharomyces Cerevisiae Sk1',
  'Pantholops Hodgsonii',
  'Oryza Longistaminata',
  'Escherichia Coli O157',
  'Populus Tremuloides',
  'Populus Sp.',
  'Populus Deltoides',
  'Papio Cynocephalus',
  'Oryza Glumipatula',
  'Glycine Soja',
  'Prunus Persica',
  'Nicotiana',
  'Anthus Spinoletta',
  'Vulpes Lagopus',
  'Ranitomeya Imitator',
  'Schistosoma Japonicum',
  'Drosophila Sechellia',
  'Gossypium Barbadense',
  'Solanum Melongena',
  'Pseudomonas Aeruginosa Pahm4',
  'Xenotilapia Spiloptera',
  'Xenotilapia Ornatipinnis',
  'Megalops Cyprinoides',
  'Citrus X Paradisi',
  'Eimeria Tenella',
  'Chlamydomonas Reinhardtii',
  'Carollia Perspicillata',
  'Saccharomyces Boulardii',
  'Galdieria Sulphuraria',
  'Triticum Monococcum',
  'Ostreococcus Lucimarinus',
  'Brugia Malayi',
  'Dendroctonus Ponderosae',
  'Pristionchus Pacificus',
  'Drosophila Willistoni',
  'Lucilia Cuprina',
  'Drosophila Ananassae',
  'Culicoides Sonorensis',
  'Orchesella Cincta',
  'Corchorus Capsularis',
  'Esox Lucius',
  'Scleropages Formosus',
  'Junco Hyemalis',
  'Calidris Pugnax',
  'Melopsittacus Undulatus',
  'Cyprinodon Variegatus',
  'Dromaius Novaehollandiae',
  'Daucus Carota',
  'Oryza Glaberrima',
  'Equus Asinus Asinus',
  'Selaginella Moellendorffii',
  'Triticum Urartu',
  'Oryza Brachyantha',
  'Polyodon Spathula',
  'Leersia Perrieri',
  'Oryza Rufipogon',
  'Camponotus Planatus',
  'Beta Vulgaris',
  'Pristionchus Arcanus',
  'Pristionchus Maxplancki',
  'Pristionchus Fukushimae',
  'Pristionchus Atlanticus',
  'Neotoma Stephensi',
  'Homo Sapiens/mus Musculus Xenograft',
  'Hylobates Lar',
  'Shewanella Oneidensis',
  'Picea Abies',
  'Fusarium Fujikuroi Imi 58289',
  'Homo Sapiens',
  'Fusarium Proliferatum Et1',
  'Sorghum',
  'Acomys Cahirinus',
  'Pelodiscus Sinensis Japonicus',
  'Human T-lymphotropic Virus 1',
  'Chlorocebus Aethiops',
  'Rattus Norvegicus Albus',
  'Schizosaccharomyces Pombe 972h-',
  'Triticum Turgidum Subsp. Dicoccoides',
  'Rattus Rattus',
  'Mouse-rat Heterokaryon',
  'Mus Saxicola',
  'Bubalus Bubalis',
  'Aegilops Tauschii X Triticum Turgidum',
  'Attacus Atlas',
  'Pteropus Alecto',
  'Sus Scrofa Domesticus',
  'Bovine Leukemia Virus',
  'Pan Paniscus',
  'Rorippa Amphibia X Rorippa Sylvestris',
  'Xenopus Borealis',
  'Saccharomyces Cerevisiae Cen.pk113-7d',
  'Xenopus Laevis X Xenopus Muelleri',
  'Staphylococcus Aureus Subsp. Aureus Str. Newman',
  'Hordeum Vulgare Subsp. Spontaneum',
  'Sorghum Bicolor',
  'Saccharomyces Bayanus',
  'Populus Alba',
  'Populus',
  'Saccharomyces Cerevisiae X Saccharomyces Kudriavzevii',
  'Populus Fremontii X Populus Angustifolia',
  'Festuca Arundinacea',
  'Theropithecus Gelada',
  'Saccharum Hybrid Cultivar N19',
  'Arabidopsis',
  'Brassica Oleracea Var. Italica',
  'Escherichia Coli Str. K-12 Substr. W3110',
  'Toxoplasma Gondii',
  'Salix Matsudana',
  'Populus Maximowiczii X Populus Nigra',
  'Populus Nigra',
  'Canis Lupus',
  'Bos Grunniens',
  'Trifolium Pratense',
  'Brachypodium Distachyon',
  'Physcomitrella Patens',
  'Gossypium Raimondii',
  'Phaseolus Vulgaris',
  'Aegilops Tauschii',
  'Citrus Reticulata',
  'Oophaga Pumilio',
  'Citrus Clementina',
  'Poecilia Latipinna',
  'Sphenodon Punctatus',
  'Candida Parapsilosis',
  'Citrus X Tangelo',
  "Populus Sp. Cv. 'walker'",
  'Arabidopsis Lyrata',
  'Rorippa Amphibia',
  'Eptesicus Fuscus',
  'Sciurus Vulgaris',
  'Drosophila Santomea',
  'Pseudomonas Aeruginosa Ucbpp-pa14',
  'Arvicanthis Niloticus',
  'Lactobacillus Delbrueckii Subsp. Bulgaricus',
  'Nannospalax Galili',
  'Salmonella Enterica Subsp. Enterica Serovar Typhimurium Str. Sl1344',
  'Vitis Girdiana',
  'Helicobacter Pylori Nctc 11637 = Ccug 17874 = Atcc 43504',
  'Loa Loa',
  'Heliconius Melpomene',
  'Anoplophora Glabripennis',
  'Trichinella Spiralis',
  'Notechis Scutatus',
  'Oryzias Melastigma',
  'Zonotrichia Albicollis',
  'Salmonella Enterica',
  'Schmidtea Mediterranea',
  'Daubentonia Madagascariensis',
  'Nycticebus Coucang',
  'Pseudomonas Aeruginosa',
  'Unidentified Influenza Virus',
  'Enterobacterio Phage Ms2',
  'Didelphis Virginiana',
  'Insect Gut Metagenome',
  'Oryza Sativa',
  'Chondrus Crispus',
  'Cucumis Sativus',
  'Amborella Trichopoda',
  'Vigna Angularis',
  'Vigna Radiata',
  'Dioscorea Rotundata',
  'Mesocricetus Auratus',
  'Arabidopsis Thaliana X Arabidopsis Lyrata',
  'Nomascus Leucogenys',
  'Synthetic Construct',
  'Granulibacter Bethesdensis',
  'Secale Cereale X Triticum Turgidum Subsp. Durum',
  'Papio Hamadryas',
  'Saccharomyces Cerevisiae S288c',
  'Mus Cervicolor',
  'Mus Cookii',
  'Candida Albicans',
  'Ceratomia Undulosa',
  'Gorilla Gorilla',
  'Oryza Sativa Japonica',
  'Spea Bombifrons',
  'Saccharomyces Uvarum',
  'Leymus Cinereus',
  'Festuca Brevipila',
  'Saccharomyces Cerevisiae By4741',
  'Escherichia Coli Uti89',
  'Vitis Rotundifolia',
  'Plasmodium Falciparum 3d7',
  'Oryza Meridionalis',
  'Escherichia Coli B Str. Rel606',
  'Actinidia Chinensis',
  'Escherichia Coli Str. K-12 Substr. Mc4100',
  'Arabidopsis Halleri',
  'Medicago Truncatula',
  'Aloe Vera',
  'Arabidopsis Lyrata Subsp. Lyrata',
  'Musa Sp.',
  'Populus Trichocarpa X Populus Deltoides',
  'Macaca Fuscata',
  'Ascaris Suum',
  'Blarina Brevicauda',
  'Peromyscus Leucopus',
  'Erethizon Dorsatum',
  'Nannospalax Ehrenbergi',
  'Drosophila Yakuba',
  'Gossypium',
  'Citrus Limon',
  'Pseudomonas Aeruginosa Tbcf10839',
  'Cardamine Sp. Sim-2007',
  'Bacillus Subtilis Subsp. Subtilis Str. Ncib 3610',
  'Bacillus Subtilis',
  'Human Poliovirus 1',
  'Leishmania Mexicana',
  'Mouse-rat Synkaryon',
  'Varecia Variegata Variegata',
  'Belgica Antarctica',
  'Nasonia Vitripennis',
  'Lepeophtheirus Salmonis',
  'Culex Quinquefasciatus',
  'Onchocerca Volvulus',
  'Caenorhabditis Japonica',
  'Trichoplax Adhaerens',
  'Pediculus Humanus',
  'Drosophila Mojavensis',
  'Caenorhabditis Remanei',
  'Atta Cephalotes',
  'Bombyx Mori',
  'Bombus Impatiens',
  'Caenorhabditis Briggsae',
  'Anopheles Darlingi',
  'Mayetiola Destructor',
  'Lottia Gigantea',
  'Caenorhabditis Brenneri',
  'Mnemiopsis Leidyi',
  'Daphnia Pulex',
  'Schistosoma Mansoni',
  'Crassostrea Gigas',
  'Zootermopsis Nevadensis',
  'Bombus Terrestris',
  'Aedes Aegypti',
  'Strigamia Maritima',
  'Drosophila Pseudoobscura',
  'Solenopsis Invicta',
  'Daphnia Magna',
  'Mola Mola',
  'Amphilophus Citrinellus',
  'Octopus Bimaculoides',
  'Stegastes Partitus',
  'Gambusia Affinis',
  'Fundulus Heteroclitus',
  'Populus Trichocarpa',
  'Manacus Vitellinus',
  'Periophthalmus Magnuspinnatus',
  'Candida Albicans Sc5314',
  'Macaca Mulatta',
  'Vitis Vinifera',
  'Triticum Aestivum',
  'Hordeum Vulgare',
  'Cercocebus Atys',
  'Mus Musculus Musculus X M. M. Domesticus',
  'Other Sequences',
  'Triticum Turgidum',
  'Lycopersicon Esculentum',
  'Solanum Pennellii',
  'Festuca Rubra Subsp. Littoralis',
  'Helicobacter Pylori',
  'Mus Macedonicus',
  'Xenopus Laevis X Xenopus Borealis',
  'Hepatovirus A',
  'Aspergillus Fumigatus',
  'Darapsa Myron',
  'Human Immunodeficiency Virus',
  'Trichomonas Vaginalis',
  'Human Immunodeficiency Virus 1',
  'Pongo Pygmaeus',
  'Homo Sapiens X Mus Musculus Hybrid Cell Line',
  'Oenococcus Oeni',
  'Staphylococcus Aureus Subsp. Aureus N315',
  'Staphylococcus Aureus Subsp. Aureus Mu50',
  'Elymus Repens',
  'Solanum Tuberosum',
  'Saccharum Hybrid Cultivar Q117',
  'Populus Euphratica',
  "Populus Sp. Cv. 'okanese'",
  'Vigna Subterranea',
  'Helianthus Annuus',
  'Hepatitis C Virus Subtype 1a',
  'Solanum Lycopersicum X Solanum Pennellii',
  'Aspergillus Niger',
  'Citrus Reticulata X Citrus Trifoliata',
  'Citrus Unshiu',
  'Brassica Napus',
  'Eulemur Coronatus',
  'Sciurus Niger',
  'Castor Canadensis',
  'Sigmodon Hispidus',
  'Papio',
  'Drosophila Simulans',
  'Pseudomonas Aeruginosa Pa14',
  'Gossypium Herbaceum',
  'Mastomys Natalensis',
  'Candida Albicans Wo-1',
  'Mycoplasma Pneumoniae',
  'Onychomys Torridus',
  'Erwinia Sp.',
  'Rhodnius Prolixus',
  'Melitaea Cinxia',
  'Capitella Teleta',
  'Thelohanellus Kitauei',
  'Megaselia Scalaris',
  'Sarcoptes Scabiei',
  'Drosophila Virilis',
  'Drosophila Grimshawi',
  'Tetranychus Urticae',
  'Tribolium Castaneum',
  'Stegodyphus Mimosarum',
  'Folsomia Candida',
  'Apteryx Owenii',
  'Lonchura Striata Domestica',
  'Neolamprologus Brichardi',
  'Pundamilia Nyererei',
  'Numida Meleagris',
  'Amphiprion Percula',
  'Anabas Testudineus',
  'Rhizopus Delemar',
  'Poecilia Mexicana',
  'Cyanidioschyzon Merolae',
  'Oryza Barthii',
  'Musa Acuminata',
  'Setaria Italica',
  'Dama Dama',
  'Bos Mutus',
  'Brassica Rapa',
  'Mus Spicilegus',
  'Lupinus Angustifolius',
  'Oryza Nivara',
  'Nicotiana Attenuata',
  'Oryza Punctata',
  'Leptosphaeria Maculans',
  'Escherichia Coli K-12',
  'Xenopus Laevis',
  'Saccharomyces Cerevisiae',
  'Ovis Aries',
  'Drosophila Melanogaster',
  'Schizosaccharomyces Pombe',
  'Caenorhabditis Elegans',
  'Danio Rerio',
  'Bos Taurus',
  'Gallus Gallus',
  'Pseudomonas Virus Phikz',
  'Candida Dubliniensis',
  'Streptococcus Gordonii',
  'Bos Indicus',
  'Rousettus Aegyptiacus',
  'Salmonella Enterica Subsp. Enterica Serovar Typhi Str. Ty2',
  'Mycobacterium Tuberculosis',
  'Streptococcus Pneumoniae Tigr4',
  'Protopterus Dolloi',
  'Oncorhynchus Mykiss',
  'Neoceratodus Forsteri',
  'Condylura Cristata',
  'Rhinolophus Sinicus',
  'Cuscuta Campestris',
  'Cyanophora Paradoxa',
  'Klebsormidium Nitens',
  'Porphyridium Purpureum',
  'Coprinopsis Cinerea',
  'Laccaria Bicolor',
  'Phycomyces Blakesleeanus',
  'Postia Placenta',
  'Uncinocarpus Reesii',
  'Volvox Carteri',
  'Chlorella Variabilis',
  'Equisetum Arvense',
  'Schrenkiella Parvula',
  'Tamias Striatus',
  'Odontomachus Ruginodis',
  'Ooceraea Biroi',
  'Spinacia Oleracea',
  'Actinidia Arguta',
  'Actinidia Eriantha',
  'Citrullus Lanatus',
  'Cucurbita Maxima',
  'Heliconius',
  'Chlamydomonas Acidophila',
  'Colletotrichum Tofieldiae',
  'Colletotrichum Incanum',
  'Pseudoperonospora Cubensis',
  'Arabidopsis Arenosa',
  'Arabidopsis Arenosa X Arabidopsis Thaliana',
  'Arabidopsis Suecica',
  'Cucurbita Moschata',
  'Fragaria Vesca',
  'Pyrus X Bretschneideri',
  'Cucumis Melo',
  'Musa Acuminata Aaa Group',
  'Malus Domestica',
  'Pristionchus Entomophagus',
  'Elaeis Guineensis',
  'Mauritia Flexuosa',
  'Musa Beccarii',
  'Olea Europaea Subsp. Europaea',
  'Olea Europaea Subsp. Cuspidata',
  'Phillyrea Angustifolia',
  'Eremopyrum Bonaepartis',
  'Taeniatherum Caput-medusae',
  'Sorghum Brachypodum',
  'Cenchrus Americanus',
  'Cenchrus Polystachios',
  'Illicium Parviflorum',
  'Illicium Floridanum',
  'Austrobaileya Scandens',
  'Ceratophyllum Demersum',
  'Canella Winterana',
  'Drimys Winteri',
  'Laurelia Sempervirens',
  'Calycanthus Floridus',
  'Idiospermum Australiense',
  'Gomortega Keule',
  'Gyrocarpus Americanus',
  'Cinnamomum Camphora',
  'Sassafras Albidum',
  'Lindera Benzoin',
  'Persea Borbonia',
  'Cassytha Filiformis',
  'Peumus Boldus',
  'Annona Muricata',
  'Uvaria Microcarpa',
  'Vitis Hybrid Cultivar',
  'Citrus Sinensis',
  'Lepidium Sativum',
  'Plasmodium Falciparum',
  'Macaca Fascicularis',
  'Pseudomonas Aeruginosa Pao1',
  'Oryza Sativa Indica Group',
  'Zea Mays',
  'Populus X Canadensis',
  'Anopheles Gambiae',
  'Vibrio Cholerae C6706',
  'Pseudomonas Aeruginosa Pak',
  'Paracoccidioides Brasiliensis',
  'Eupomatia Bennettii',
  'Piper Auritum',
  'Peperomia Fraseri',
  'Frankenia Laevis',
  'Buxus Sempervirens',
  'Meliosma Cuneifolia',
  'Hypecoum Procumbens',
  'Litopenaeus Vannamei',
  'Vitis Palmata',
  'Vitis Riparia X Vitis Rupestris',
  'Mus Musculus',
  'Pristionchus Fissidentatus',
  'Pristionchus Hoplostomus',
  'Pristionchus Maupasi',
  'Parapristionchus Giblindavisi',
  'Cyprinodon Desquamator',
  'Cyprinodon Brontotheroides',
  'Human Metagenome',
  'Michelia Maudiae',
  'Sanguinaria Canadensis',
  'Equus Caballus',
  'Agraulis Vanillae',
  'Pristionchus Boliviae',
  'Pristionchus Lucani',
  'Escherichia Coli Str. K-12 Substr. Mg1655',
  'Populus Tremula X Populus Alba',
  'Glycine Max',
  'Acinetobacter Baumannii',
  'Klebsiella Pneumoniae',
  'Magnolia Grandiflora',
  'Myristica Fragrans',
  'Aristolochia Elegans',
  'Saururus Cernuus',
  'Grevillea Robusta',
  'Nandina Domestica',
  'Euptelea Pleiosperma',
  'Papaver Bracteatum',
  'Pseudomonas Aeruginosa Pacs2',
  'Chlorocebus Pygerythrus',
  'Corchorus Olitorius',
  'Bicosoecida Sp. Cb-2014',
  'Dinobryon',
  'Alexandrium Fundyense',
  'Amphora Coffeiformis',
  'Cyclophora Tenuis',
  'Ascarina Rubricaulis',
  'Trochodendron Aralioides',
  'Argemone Mexicana',
  'Amphidinium Carterae',
  'Pseudo-nitzschia Fraudulenta',
  'Perkinsus Marinus',
  'Gouania Willdenowi',
  'Goniomonas',
  'Hakea Prostrata',
  'Cocculus Laurifolius',
  'Scrippsiella Hangoei',
  'Tetranychus Pueraricola',
  'Tetranychus Merganser',
  'Tetranychus Piercei',
  'Tetranychus Misumaiensis',
  'Tetranychus Neocaledonicus',
  'Oligonychus Camelliae',
  'Oligonychus Biharensis',
  'Panonychus Citri',
  'Tetranychus Evansi',
  'Oligonychus Rubicundus',
  'Aponychus Corpuzae',
  'Schizotetranychus Bambusae',
  'Amphitetranychus Viennensis',
  'Eotetranychus Asiaticus',
  'Schizotetranychus Gilvus',
  'Amphitetranychus Quercivorus',
  'Tetranychus Bambusae',
  'Gossypium Thurberi',
  'Corethron Hystrix',
  'Parambassis Ranga',
  'Skeletonema Costatum',
  'Nitzschia',
  'Cottoperca Gobio',
  'Cryptomonas Paramecium',
  'Guillardia Theta',
  'Ditylum Brightwellii',
  'Echeneis Naucrates',
  'Pholidichthys Leucotaenia',
  'Picocystis Salinarum',
  'Myripristis Murdjan',
  'Phaeomonas Parva',
  'Salarias Fasciatus',
  'Chelmon Rostratus',
  'Dunaliella Tertiolecta',
  'Florenciella',
  'Florenciella Parvula',
  'Apocalathium Aciculiferum',
  'Chaetoceros Affinis',
  'Chaetoceros Curvisetus',
  'Chlamydomonas Leiostraca',
  'Chlamydomonas Chlamydogama',
  'Akashiwo Sanguinea',
  'Gymnodinium Catenatum',
  'Striatella Unipunctata',
  'Astrosyne Radiata',
  'Hakea Drupacea',
  'Platanus Occidentalis',
  'Akebia Trifoliata',
  'Capnoides Sempervirens',
  'Papaver Rhoeas',
  'Papaver Setigerum',
  'Corydalis Linstowiana',
  'Chelidonium Majus',
  'Hydrastis Canadensis',
  'Cimicifuga Racemosa',
  'Anemone Hupehensis',
  'Thalictrum Thalictroides',
  'Anemone Pulsatilla',
  'Gunnera Manicata',
  'Aextoxicon Punctatum',
  'Berberidopsis Beckleri',
  'Dillenia Indica',
  'Hibbertia Grossulariifolia',
  'Delosperma Echinatum',
  'Cypselea Humifusa',
  'Sesuvium Portulacastrum',
  'Sesuvium Verrucosum',
  'Trianthema Portulacastrum',
  'Zaleya Pentandra',
  'Aerva Lanata',
  'Aerva Persica',
  'Amaranthus Palmeri',
  'Amaranthus Tricolor',
  'Amaranthus Retroflexus',
  'Blutaparon Vermiculare',
  'Atriplex Hortensis',
  'Atriplex Prostrata',
  'Atriplex Rosea',
  'Chenopodium Quinoa',
  'Alternanthera Brasiliana',
  'Alternanthera Caracasana',
  'Alternanthera Sessilis',
  'Alternanthera Tenella',
  'Beta Maritima',
  'Ancistrocladus Tectorius',
  'Basella Alba',
  'Pereskia Aculeata',
  'Lophophora Williamsii',
  'Opuntia Polyacantha',
  'Saponaria Officinalis',
  'Polycarpaea Repens',
  'Spergularia Media',
  'Schiedea Membranacea',
  'Dianthus Caryophyllus',
  'Silene Latifolia',
  'Mollugo Cerviana',
  'Mollugo Nudicaulis',
  'Mollugo Pentaphylla',
  'Mollugo Verticillata',
  'Nepenthes Alata',
  'Bougainvillea Spectabilis',
  'Allionia Incarnata',
  'Boerhavia Coccinea',
  'Boerhavia Burbidgeana',
  'Elodea Nuttallii',
  'Mirabilis Jalapa',
  'Physena Madagascariensis',
  'Phytolacca Americana',
  'Petiveria Alliacea',
  'Phytolacca Bogotensis',
  'Microtea Debilis',
  'Hilleria Latifolia',
  'Plumbago Auriculata',
  'Limonium Spectabile',
  'Polygonum Convolvulus',
  'Portulaca Oleracea',
  'Portulaca Amilis',
  'Portulaca Cryptopetala',
  'Portulaca Grandiflora',
  'Portulaca Umbraticola',
  'Portulaca Molokiniensis',
  'Portulaca Pilosa',
  'Portulaca Suffrutescens',
  'Sarcobatus Vermiculatus',
  'Simmondsia Chinensis',
  'Tamarix Chinensis',
  'Balanophora Fungosa',
  'Ximenia Americana',
  'Dendropemon Caribaeus',
  'Santalum Acuminatum',
  'Exocarpos Cupressiformis',
  'Phoradendron Serotinum',
  'Hamamelis Virginiana',
  'Loropetalum Chinense',
  'Alangium Chinense',
  'Liquidambar Styraciflua',
  'Cercidiphyllum Japonicum',
  'Rhodiola Rosea',
  'Crassula Perforata',
  'Daphniphyllum Macropodum',
  'Myriophyllum Aquaticum',
  'Aphanopetalum Resinosum',
  'Itea Virginica',
  'Paeonia Lactiflora',
  'Saxifraga Stolonifera',
  'Heuchera Sanguinea',
  'Oresitrophe Rupifraga',
  'Mitella Pentandra',
  'Heteropyxis Natalensis',
  'Tetrazygia Bicolor',
  'Syzygium Paniculatum',
  'Syzygium Micranthum',
  'Krameria Lanceolata',
  'Thladiantha Villosula',
  'Coriaria Nepalensis',
  'Gompholobium Polymorphum',
  'Juglans Nigra',
  'Myrica Cerifera',
  'Mammea Americana',
  'Garcinia Livingstonei',
  'Manihot Grahamii',
  'Euphorbia Mesembryanthemifolia',
  'Linum Lewisii',
  'Linum Leonii',
  'Linum Macraei',
  'Linum Bienne',
  'Rhodosorus Marinus',
  'Odontella Aurita',
  'Cylindrotheca Closterium',
  'Eutreptiella Gymnastica',
  'Rhinatrema Bivittatum',
  'Amphilophus Amarillo',
  'Palpitomonas Bilix',
  'Prymnesium Parvum',
  'Acanthoeca',
  'Sphaeramia Orbicularis',
  'Melanotaenia Boesemani',
  'Scatophagus Argus',
  'Helicotheca Tamesis',
  'Uncultured Eukaryote',
  'Thalassiosira Oceanica',
  'Simochromis Diagramma',
  'Anophryoides Haemophila',
  'Chrysoreinhardia',
  'Aplanochytrium Stocchinoi',
  'Blepharisma Japonicum',
  'Conticribra Weissflogii',
  'Micromonas',
  'Tetraselmis Astigmatica',
  'Geminigera Cryophila',
  'Myrionecta Rubra',
  'Dinophysis Acuminata',
  'Pyrodinium Bahamense',
  'Amoebophrya Sp.',
  'Alexandrium Catenella',
  'Rhizosolenia Setigera',
  'Thalassionema Frauenfeldii',
  'Triparma Pacifica',
  'Pseudo-nitzschia Delicatissima',
  'Sorites Sp.',
  'Chlorarachnion Reptans',
  'Protoceratium Reticulatum',
  'Togula Jolla',
  'Polarella Glacialis',
  'Vannella Sp. Cb-2014',
  'Vannella',
  'Ochromonas',
  'Strombidinopsis',
  'Trichosphaerium',
  'Filamoeba Nolandi',
  'Pessonella',
  'Pelagomonas Calceolata',
  'Skeletonema Dohrnii',
  'Boykinia Jamesii',
  'Astilbe Chinensis',
  'Tetrastigma Obtectum',
  'Geranium Maculatum',
  'Greyia Sutherlandii',
  'Punica Granatum',
  'Medinilla Magnifica',
  'Eucalyptus Leucoxylon',
  'Bituminaria Bituminosa',
  'Betula Pendula',
  'Fagus Sylvatica',
  'Quercus Shumardii',
  'Castanea Crenata',
  'Carya Glabra',
  'Licania Michauxii',
  'Garcinia Oblongifolia',
  'Linum Grandiflorum',
  'Linum Flavum',
  'Linum Perenne',
  'Aponychus Firmianae',
  'Stigmaeopsis Miscanthi',
  'Eotetranychus Pruni',
  'Eotetranychus Uncatus',
  'Eotetranychus Toyoshimai',
  'Schizotetranychus Cercidiphylli',
  'Panonychus Osmanthi',
  'Panonychus Pusillus',
  'Tetranychus Lombardinii',
  'Oligonychus Ilicis',
  'Tetranychus Turkestani',
  'Tetranychus Phaselus',
  'Tetranychus Zeae',
  'Tetranychus Huhhotensis',
  'Stigmaeopsis Celarius',
  'Tetranychus Parakanzawai',
  'Tetranychus Ezoensis',
  'Tetranychus Macfarlanei',
  'Oligonychus Hondoensis',
  'Eotetranychus Nomurai',
  'Stigmaeopsis Saharai',
  'Panonychus Bambusicola',
  'Oligonychus Orthius',
  'Schizotetranychus Shii',
  'Petrobia Latens',
  'Tetranychus Okinawanus',
  'Panonychus Mori',
  'Schizotetranychus Recki',
  'Amatitlania Siquia',
  'Hypsophrys Nematopus',
  'Hypsophrys Nicaraguensis',
  'Denticeps Clupeoides',
  'Acanthurus Nigricans',
  'Aplanochytrium',
  'Karenia Brevis',
  'Skeletonema Marinoi',
  'Paraphysomonas Imperforata',
  'Percolomonas Cosmopolitus',
  'Prorocentrum Minimum',
  'Thalassiosira Rotula',
  'Mesodinium Pulex',
  'Alexandrium Tamarense',
  'Tiarina Fusa',
  'Heterosigma Akashiwo',
  'Tiarella Polyphylla',
  'Tetrastigma Voinierianum',
  'Terminalia Neotaliala',
  'Lagerstroemia Indica',
  'Acacia Pycnantha',
  'Astragalus Propinquus',
  'Nothofagus Obliqua',
  'Chrysobalanus Icaco',
  'Hypericum Perforatum',
  'Linum Strictum',
  'Passiflora Edulis',
  'Passiflora Caerulea',
  'Drypetes Deplanchei',
  'Pseudo-nitzschia Arenysensis',
  'Tetraselmis Striata',
  'Sus Scrofa Scrofa',
  'Schizotetranychus Schizopus',
  'Eotetranychus Rubricans',
  'Eotetranychus Suginamensis',
  'Panonychus Caglei',
  'Tetranychus Kanzawai',
  'Eotetranychus Smithi',
  'Eutetranychus Africanus',
  'Bryobia Praetiosa',
  'Oligonychus Gotohi',
  'Stigmaeopsis Longus',
  'Panonychus Akitanus',
  'Petrobia Harti',
  'Capsella Rubella',
  'Stachyurus Praecox',
  'Geranium Carolinianum',
  'Francoa Appendiculata',
  'Glycyrrhiza Lepidota',
  'Acacia Argyrophylla',
  'Bischofia Javanica',
  'Rhizophora Mangle',
  'Mus Mattheyi',
  'Apodemus Uralensis',
  'Selaginella Kraussiana',
  'Leptocylindrus Aporus',
  'Stigmaeopsis Takahashii',
  'Panonychus Thelytokus',
  'Eotetranychus Querci',
  'Eotetranychus Tiliaecola',
  'Eotetranychus Dissectus',
  'Bryobia Eharai',
  'Eotetranychus Uchidai',
  'Yezonychus Sapporensis',
  'Schizotetranychus Lespedezae',
  'Tetranychus Ludeni',
  'Panonychus Ulmi',
  'Oligonychus Amiensis',
  'Tetranychus Truncatus',
  'Oligonychus Coffeae',
  'Amphilophus Astorquii',
  'Strigops Habroptila',
  'Balaenoptera Musculus',
  'Lynx Canadensis',
  'Archocentrus Centrarchus',
  'Leptocylindrus Danicus',
  'Goniomonas Pacifica',
  'Pteridomonas Danica',
  'Prymnesium Polylepis',
  'Chrysochromulina Rotalis',
  'Peltoboykinia Watanabei',
  'Tellima Breviflora',
  'Cissus Quadrangularis',
  'Staphylea Trifolia',
  'Melaleuca Quinquenervia',
  'Chamerion Angustifolium',
  'Crossopetalum Rhacoma',
  'Wisteria Floribunda',
  'Gleditsia Sinensis',
  'Casuarina Equisetifolia',
  'Castanea Pumila',
  'Ricinus Communis',
  'Croton Tiglium',
  'Euphorbia Pekinensis',
  'Linum Usitatissimum',
  'Linum Hirsutum',
  'Linum Tenuifolium',
  'Galphimia Gracilis',
  'Malesherbia Fasciculata',
  'Ochna Mossambicensis',
  'Ochna Serrulata',
  'Erythroxylum Coca',
  'Salix Acutifolia',
  'Salix Dasyclados',
  'Salix Eriocephala',
  'Salix Purpurea',
  'Salix Sachalinensis',
  'Salix Viminalis',
  'Salix Fargesii',
  'Viola Tricolor',
  'Viola Canadensis',
  'Cephalotus Follicularis',
  'Cunonia Capensis',
  'Elaeocarpus Sylvestris',
  'Cannabis Sativa',
  'Humulus Lupulus',
  'Celtis Occidentalis',
  'Elaeagnus Pungens',
  'Morus Nigra',
  'Ficus Religiosa',
  'Rhamnus Japonica',
  'Rhamnus Caroliniana',
  'Ziziphus Jujuba',
  'Rosa Palustris',
  'Sanguisorba Minor',
  'Geum Quellyon',
  'Prunus Prostrata',
  'Kerria Japonica',
  'Sorbus Koehneana',
  'Amelanchier Canadensis',
  'Arabidopsis Thaliana X Arabidopsis Arenosa',
  'Cotoneaster Transcaucasicus',
  'Physocarpus Opulifolius',
  'Aruncus Dioicus',
  'Dryas Octopetala',
  'Cercocarpus Ledifolius',
  'Urtica Dioica',
  'Tapiscia Sinensis',
  'Akania Lucens',
  'Batis Maritima',
  'Brassica Nigra',
  'Sinapis Alba',
  'Cochlearia Officinalis',
  'Arabis Alpina',
  'Draba Aizoides',
  'Draba Magellanica',
  'Draba Sachalinensis',
  'Draba Hispida',
  'Draba Oligosperma',
  'Draba Ossetica',
  'Cleome Violacea',
  'Cleome Gynandra',
  'Cleome Viscosa',
  'Gyrostemon Ramulosus',
  'Koeberlinia Spinosa',
  'Limnanthes Douglasii',
  'Moringa Oleifera',
  'Reseda Odorata',
  'Tropaeolum Peregrinum',
  'Bixa Orellana',
  'Dombeya Burgessiae',
  'Hoheria Angustifolia',
  'Muntingia Calabura',
  'Wikstroemia Indica',
  'Daphne Giraldii',
  'Edgeworthia Papyrifera',
  'Rhus Radicans',
  'Litchi Chinensis',
  'Bursera Simaruba',
  'Boswellia Sacra',
  'Kirkia Wilmsii',
  'Azadirachta Indica',
  'Melia Azedarach',
  'Peganum Harmala',
  'Phellodendron Amurense',
  'Aesculus Pavia',
  'Acer Negundo',
  'Quassia Amara',
  'Ailanthus Altissima',
  'Cornus Florida',
  'Camptotheca Acuminata',
  'Nyssa Ogeche',
  'Curtisia Dentata',
  'Dichroa Febrifuga',
  'Hydrangea Quercifolia',
  'Galax Urceolata',
  'Souroubea Exauriculata',
  'Isoetes Drummondii',
  'Selaginella Martensii',
  'Parachromis Managuensis',
  'Pristionchus Exspectatus',
  'Cribroheros Rostratus',
  'Hydra Vulgaris',
  'Scrippsiella Trochoidea',
  'Sexangularia Sp. Cb-2014',
  'Euplotes Focardii',
  'Philadelphus Inodorus',
  'Cavendishia Cuatrecasasii',
  'Rhododendron Scopulorum',
  'Amphilophus Zaliosus',
  'Amphilophus Sagittae',
  'Skeletonema Menzelii',
  'Pelagococcus Subviridis',
  'Extubocellulus Spinifer',
  'Aristerostoma',
  'Fragilariopsis Kerguelensis',
  'Thalassiosira Antarctica',
  'Rhodella Violacea',
  'Amphiprora',
  'Amorphochlora Amoebiformis',
  'Paramoeba Atlantica',
  'Paramoeba Aestuarina',
  'Chaetoceros Sp.',
  'Alexandrium Monilatum',
  'Condylostoma Magnum',
  'Isochrysis Galbana',
  'Platyophrya Macrostoma',
  'Euplotes Harpa',
  'Pseudokeronopsis',
  'Corethron Pennatum',
  'Proboscia Alata',
  'Noctiluca Scintillans',
  'Norrisiella Sphaerica',
  'Dactyliosolen Fragilissimus',
  'Chlamydomonas Euryale',
  'Vaucheria Litorea',
  'Perkinsus Chesapeaki',
  'Deutzia Scabra',
  'Caiophora Chuquitensis',
  'Cyrilla Racemiflora',
  'Melica Nutans',
  'Nassella Pulchra',
  'Asterionellopsis Glacialis',
  'Heterocapsa Rotundata',
  'Equus Caballus X Asinus',
  'Favella Ehrenbergii',
  'Phyllostomus Discolor',
  'Hippoglossus Hippoglossus',
  'Amblyraja Radiata',
  'Calypte Anna',
  'Chiroxiphia Lanceolata',
  'Dermochelys Coriacea',
  'Strombidinopsis Acuminata',
  'Durinskia Baltica',
  'Crustomastix Stigmatica',
  'Prasinoderma Coloniale',
  'Chroomonas Cf. Mesostigmatica',
  'Rhodomonas Lens',
  'Tetraselmis Chuii',
  'Schmidingerella Taraikaensis',
  'Oxyrrhis Marina',
  'Litonotus Pictus',
  'Alexandrium Margalefii',
  'Thalassiosira Minuscula',
  'Chromis Viridis',
  'Prasinococcus Capsulatus',
  'Thoracosphaera Heimii',
  'Emiliania Huxleyi',
  'Chattonella Subsalsa',
  'Ostreococcus Mediterraneus',
  'Bathycoccus Prasinos',
  'Ledum Palustre',
  'Fouquieria Macdougalii',
  'Maesa Lanceolata',
  'Brachypodium Stacei',
  'Heliconius Erato',
  'Acromyrmex Echinatior',
  'Nuphar Advena',
  'Sarcandra Glabra',
  'Eschscholzia Californica',
  'Cunninghamia Lanceolata',
  'Cedrus Libani',
  'Selaginella Stauntoniana',
  'Bryum Argenteum',
  'Brachypodium Hybridum',
  'Anopheles Marajoara',
  'Anopheles Braziliensis',
  'Anopheles Nuneztovari',
  'Lotharella Oceanica',
  'Aureoumbra Lagunensis',
  'Protocruzia Adherens',
  'Proboscia Inermis',
  'Tryblionella Compressa',
  'Chaetoceros Neogracilis',
  'Kryptoperidinium Foliaceum',
  'Thraustochytrium Sp.',
  'Pseudo-nitzschia Australis',
  'Dolichomastix Tenuilepis',
  'Stephanopyxis Turris',
  'Lotharella Globosa',
  'Bigelowiella Natans',
  'Strombidium Rassoulzadegani',
  'Polytomella Parva',
  'Mayorella',
  'Gymnochlora',
  'Strombidium Inclinatum',
  'Debaryomyces Hansenii',
  'Alveolata',
  'Chromera Velia',
  'Gloeochaete Wittrockiana',
  'Compsopogon Caeruleus',
  'Cafeteria Roenbergensis',
  'Sarcodes Sanguinea',
  'Anopheles Triannulatus',
  'Nardus Stricta',
  'Nicotiana Obtusifolia',
  'Hemiselmis Andersenii',
  'Sitophilus Oryzae',
  'Diplazium Esculentum',
  'Asplenium Nidus',
  'Pteris Vittata',
  'Microlepia Platyphylla',
  'Azolla Caroliniana',
  'Salvinia Molesta',
  'Salvinia Cucullata',
  'Lygodium Japonicum',
  'Diplopterygium Chinense',
  'Dicranopteris Pedata',
  'Angiopteris Fokiensis',
  'Equisetum Ramosissimum',
  'Palhinhaea Cernua',
  'Isoetes Sinensis',
  'Folioceros Fuciformis',
  'Heterocapsa Triquetra',
  'Porphyridium Aerugineum',
  'Thalassiosira Gravida',
  'Alexandrium Minutum',
  'Monotropa Uniflora',
  'Ardisia Revoluta',
  'Ardisia Humilis',
  'Ternstroemia Gymnanthera',
  'Phlox Drummondii',
  'Roridula Gorgonias',
  'Synsepalum Dulcificum',
  'Manilkara Zapota',
  'Sideroxylon Reclinatum',
  'Sinojackia Xylocarpa',
  'Symplocos Tinctoria',
  'Heliotropium Calcicola',
  'Pilostyles Thurberi',
  'Heliotropium Tenuifolium',
  'Heliotropium Convolvulaceum',
  'Heliotropium Filiforme',
  'Heliotropium Greggii',
  'Heliotropium Karwinskyi',
  'Heliotropium Mendocinum',
  'Heliotropium Racemosum',
  'Heliotropium Tenellum',
  'Heliotropium Texanum',
  'Ehretia Acuminata',
  'Mertensia Paniculata',
  'Phacelia Campanularia',
  'Lennoa Madreporoides',
  'Pholisma Arenarium',
  'Pyrenacantha Malvifolia',
  'Eucommia Ulmoides',
  'Aucuba Japonica',
  'Oncotheca Balansae',
  'Apocynum Androsaemifolium',
  'Rauvolfia Tetraphylla',
  'Asclepias Syriaca',
  'Asclepias Curassavica',
  'Wrightia Natalensis',
  'Holarrhena Pubescens',
  'Gelsemium Sempervirens',
  'Exacum Affine',
  'Gentiana Acaulis',
  'Strychnos Spinosa',
  'Psychotria Ipecacuanha',
  'Morinda Citrifolia',
  'Galium Boreale',
  'Psychotria Marginata',
  'Strobilanthes Dyeriana',
  'Ruellia Brittoniana',
  'Anisacanthus Quadrifidus',
  'Tabebuia Umbellata',
  'Mansoa Alliacea',
  'Kigelia Africana',
  'Byblis Gigantea',
  'Calceolaria Pinifolia',
  'Sinningia Tuberosa',
  'Saintpaulia Ionantha',
  'Agastache Rugosa',
  'Scutellaria Montana',
  'Leonurus Japonicus',
  'Pycnanthemum Tenuifolium',
  'Lavandula Angustifolia',
  'Solenostemon Scutellarioides',
  'Vitex Agnus-castus',
  'Thymus Vulgaris',
  'Teucrium Chamaedrys',
  'Micromeria Fruticosa',
  'Nepeta Cataria',
  'Ajuga Reptans',
  'Marrubium Vulgare',
  'Melissa Officinalis',
  'Prunella Vulgaris',
  'Oxera Pulchella',
  'Poliomintha Bustamanta',
  'Oxera Neriifolia',
  'Pinguicula Agnata',
  'Pinguicula Caudata',
  'Olea Europaea',
  'Chionanthus Retusus',
  'Ligustrum Sinense',
  'Forestiera Segregata',
  'Conopholis Americana',
  'Lindenbergia Philippensis',
  'Orobanche Fasciculata',
  'Epifagus Virginiana',
  'Paulownia Fargesii',
  'Uncarina Grandidieri',
  'Rehmannia Glutinosa',
  'Digitalis Purpurea',
  'Plantago Coronopus',
  'Plantago Maritima',
  'Plantago Virginica',
  'Antirrhinum Majus',
  'Antirrhinum Braun-blanquetii',
  'Bacopa Caroliniana',
  'Schlegelia Violacea',
  'Schlegelia Parasitica',
  'Celsia Arcturus',
  'Anticharis Glandulosa',
  'Buddleja Lindleyana',
  'Polypremum Procumbens',
  'Lantana Camara',
  'Verbena Hastata',
  'Botrytis Cinerea',
  'Phyla Dulcis',
  'Ipomoea Hederacea',
  'Nicotiana Sylvestris',
  'Brugmansia Sanguinea',
  'Angelica Archangelica',
  'Ilex Paraguariensis',
  'Xanthium Strumarium',
  'Helenium Autumnale',
  'Haliotis Discus Hannai',
  'Trieres Chinensis',
  'Coccolithus Braarudii',
  'Microsorum Cuspidatum',
  'Selaginella Uncinata',
  'Houttuynia Cordata',
  'Diospyros Malabarica',
  'Juniperus Scopulorum',
  'Prumnopitys Andina',
  'Sciadopitys Verticillata',
  'Pseudolycopodiella Caroliniana',
  'Lycopodium Obscurum',
  'Vexillifera',
  'Rosalina',
  'Crypthecodinium Cohnii',
  'Amphidinium Massartii',
  'Gambierdiscus Australes',
  'Stygamoeba Regulata',
  'Chaetoceros Debilis',
  'Thalassiothrix Antarctica',
  'Thalassionema Nitzschioides',
  'Stereomyxa Ramosa',
  'Amphiprion Clarkii',
  'Grammatophora Oceanica',
  'Skeletonema Grethae',
  'Skeletonema Japonicum',
  'Lankesteria Abbotti',
  'Minchinia Chitonis',
  'Convolvulus Arvensis',
  'Ipomoea Purpurea',
  'Ipomoea Nil',
  'Ipomoea Coccinea',
  'Ipomoea Quamoclit',
  'Ipomoea Pubescens',
  'Ipomoea Indica',
  'Ipomoea Lobata',
  'Kaliphora Madagascariensis',
  'Atropa Belladonna',
  'Solanum Ptychanthum',
  'Solanum Dulcamara',
  'Solanum Xanthocarpum',
  'Lycium Barbarum',
  'Lycopersicon Cheesmanii',
  'Solanum Sisymbriifolium',
  'Solanum Lasiophyllum',
  'Platyspermation Crassifolium',
  'Heracleum Lanatum',
  'Polyscias Fruticosa',
  'Griselinia Littoralis',
  'Pennantia Corymbosa',
  'Ilex Vomitoria',
  'Helwingia Japonica',
  'Corokia Cotoneaster',
  'Matricaria Matricarioides',
  'Silybum Marianum',
  'Ceratopteris Richardii',
  'Spirogyra Pratensis',
  'Perinereis Aibuhitensis',
  'Stipa Lagascae',
  'Equus Asinus',
  'Equus Asinus X Caballus',
  'Cyrtomium Fortunei',
  'Odontosoria Chinensis',
  'Alsophila Spinulosa',
  'Cibotium Barometz',
  'Vandenboschia Striata',
  'Plenasium Vachellii',
  'Psilotum Nudum',
  'Ophioglossum Vulgatum',
  'Ipomoea Lindheimeri',
  'Datura Metel',
  'Escallonia Rubra',
  'Hedera Helix',
  'Hydrocotyle Umbellata',
  'Griselinia Racemosa',
  'Centella Asiatica',
  'Pittosporum Resiniferum',
  'Conyza Canadensis',
  'Solidago Canadensis',
  'Nicotiana Acuminata',
  'Anthoceros Agrestis',
  'Marchantia Polymorpha',
  'Nicotiana Linearis',
  'Zea Mays Subsp. Mays',
  'Marchantia Polymorpha Subsp. Polymorpha',
  'Momordica Charantia',
  'Trichosanthes Kirilowii',
  'Amblygaster Clupeoides',
  'Danio Albolineatus',
  'Danio Aesculapii',
  'Branchiostoma Lanceolatum',
  'Linepithema Humile',
  'Vitis X Champinii',
  'Trichophyton Rubrum',
  'Toxoplasma Gondii B41',
  'Toxoplasma Gondii Bof',
  'Toxoplasma Gondii Cast',
  'Toxoplasma Gondii Castells',
  'Toxoplasma Gondii Type Iii',
  'Toxoplasma Gondii Coug',
  'Toxoplasma Gondii Fou',
  'Toxoplasma Gondii Gt1',
  'Toxoplasma Gondii Guy-dos',
  'Toxoplasma Gondii Guy-koe',
  'Toxoplasma Gondii Guy-mat',
  'Toxoplasma Gondii Mas',
  'Toxoplasma Gondii Me49',
  'Toxoplasma Gondii P89',
  'Toxoplasma Gondii Pru',
  'Toxoplasma Gondii Ray',
  'Toxoplasma Gondii Rh',
  'Toxoplasma Gondii Rub',
  'Toxoplasma Gondii Tgcatbr5',
  'Toxoplasma Gondii Vand',
  'Toxoplasma Gondii Veg',
  'Ateles Fusciceps',
  'Mus Musculus Gentilulus',
  'Meriones Unguiculatus',
  'Brucella Abortus 544',
  'Alligator Mississippiensis',
  'Tachyoryctes Splendens',
  'Cryptomys Hottentotus Pretoriae',
  'Cryptomys Hottentotus Natalensis',
  'Cryptococcus Gattii Vgii',
  'Cryptococcus Gattii Vgi',
  'Cryptococcus Gattii Vgiii',
  'Cryptomys Hottentotus Hottentotus',
  'Georychus Capensis',
  'Cryptococcus Gattii Vgiv',
  'Heliophobius Emini',
  'Cryptomys Hottentotus Mahali',
  'Fukomys Damarensis',
  'Salmonella Enterica Subsp. Enterica Serovar Typhimurium',
  'Mucor Circinelloides F. Lusitanicus',
  'Eurycea Nana',
  'Eurycea Neotenes',
  'Eurycea Tonkawae',
  'Cryptococcus Neoformans Var. Grubii H99',
  'Drosophila Suzukii',
  'Drosophila Melanogaster X Drosophila Sechellia',
  'Lutzomyia Longipalpis',
  'Ceratitis Capitata',
  'Drosophila Melanogaster X Drosophila Simulans',
  'Drosophila Arizonae',
  'Lucilia Sericata',
  'Drosophila Saltans',
  'Drosophila Austrosaltans',
  'Drosophila Bipectinata',
  'Drosophila Biarmipes',
  'Drosophila Kikkawai',
  'Poikilolaimus Oxycercus',
  'Phlox Pilosa',
  'Steinernema Carpocapsae',
  'Steinernema Feltiae',
  'Caenorhabditis Angaria',
  'Verticillium Dahliae',
  'Passiflora Oerstedii',
  'Citrus X Microcarpa',
  'Nicotiana Miersii',
  'Nicotiana Pauciflora',
  'Medicago Sativa',
  'Pieris Rapae',
  'Heliconius Cydno',
  'Papilio Polytes',
  'Colias Eurytheme',
  'Brassica Cretica',
  'Brassica Hilarionis',
  'Brassica Incana',
  'Brassica Insularis',
  'Brassica Macrocarpa',
  'Brassica Bourgeaui',
  'Brassica Montana',
  'Brassica Rupestris',
  'Brassica Villosa',
  'Brassica Carinata',
  'Brassica Carinata X Brassica Rapa',
  'Eutrema Salsugineum',
  'Brassica Juncea',
  'Leptosphaeria Biglobosa',
  'Boechera Depauperata',
  'Brassica Oleracea Var. Alboglabra',
  'Sclerotinia Sclerotiorum',
  'Brassicaceae',
  'Monomorium Pharaonis',
  'Acanthurus Tractus',
  'Saccharomyces Cerevisiae S96 X Yjm789',
  'Nicotiana Benthamiana',
  'Orychophragmus Violaceus',
  'Brassica Rapa Subsp. Pekinensis',
  'Brassica Rapa Subsp. Oleifera',
  'Brassica Rapa Var. Perviridis',
  'Brassica Rapa Subsp. Rapa',
  'Brassica Rapa Subsp. Trilocularis',
  'Brassica Rapa Subsp. Dichotoma',
  'Brassica Rapa Subsp. Chinensis',
  'Brassica Rapa Subsp. Narinosa',
  'Brassica Rapa Subsp. Nipposinica',
  'Brassica Rapa Var. Parachinensis',
  'Brassica Rapa X Brassica Nigra',
  'Organismal Metagenomes',
  "Leptosphaeria Maculans 'brassicae' Group",
  "Leptosphaeria Biglobosa 'brassicae' Group",
  'Acanthemblemaria Sp. Cur14058.g',
  'Amblycirrhitus Pinos',
  'Aulostomus Maculatus',
  'Aulostomus Sp. Cur14037.g',
  'Magnaporthe Oryzae',
  'Sinorhizobium Meliloti',
  'Lotus Japonicus',
  'Mesorhizobium Japonicum Maff 303099',
  'Lupinus Mutabilis',
  'Lupinus Albus',
  'Lupinus Cosentinii',
  'Lupinus Luteus',
  'Pisum Sativum',
  'Batrachomoeus Trispinosus',
  'Caranx Ignobilis',
  'Solanum Chacoense',
  'Centropomus Sp. Cur14125.g',
  'Chaetodipterus Faber',
  'Chaetodon Auriga',
  'Channa Gachua',
  'Cuscuta Australis',
  'Chrionema Squamentum',
  'Coilia Nasus',
  'Prunus Davidiana',
  'Conger Cinereus',
  'Corydoras Julii',
  'Oenothera Elata Subsp. Elata',
  'Oenothera Laciniata',
  'Papaver Somniferum',
  'Oenothera Grandis',
  'Oenothera Nana',
  'Lupinus Polyphyllus',
  'Oenothera Biennis',
  'Oenothera Picensis',
  'Oenothera Grandiflora',
  'Oenothera Filiformis',
  'Oenothera Berlandieri',
  'Oenothera Rosea',
  'Oenothera Speciosa',
  'Gleditsia Triacanthos',
  'Oenothera Affinis',
  'Astragalus Membranaceus',
  'Oenothera Villaricae',
  'Coryphopterus Lipernes',
  'Oenothera Longituba',
  'Oenothera Elata Subsp. Hookeri',
  'Oenothera Gaura',
  'Bauhinia Tomentosa',
  'Oenothera Suffulta',
  'Oenothera Clelandii',
  'Alnus Serrulata',
  'Apios Americana',
  'Quillaja Saponaria',
  'Oenothera Serrulata',
  'Acanthopagrus Latus',
  'Vitis Vinifera X Vitis Girdiana',
  'Istigobius Decoratus',
  'Lactoria Cornuta',
  'Melanotaenia Praecox',
  'Micropterus Floridanus',
  'Myripristis Berndti',
  'Neoniphon Vexillarium',
  'Opistognathus Aurifrons',
  'Oplegnathus Punctatus',
  'Oryzias Mekongensis',
  'Parambassis Pulcinella',
  'Parapercis Xanthozona',
  'Parupeneus Indicus',
  'Percopsis Omiscomaycus',
  'Peristedion Brevirostre',
  'Phaeoptyx Sp. Aa7hj72',
  'Photopectoralis Bindus',
  'Plotosus Lineatus',
  'Pomacanthus Paru',
  'Pontinus Castor',
  'Priacanthus Tayenus',
  'Pseudobalistes Fuscus',
  'Silurus Asotus',
  'Solea Ovata',
  'Synanceia Verrucosa',
  'Syngnathoides Biaculeatus',
  'Tinca Tinca',
  'Toxotes Jaculatrix',
  'Trachinotus Ovatus',
  'Lathyrus Sativus',
  'Senna Hebecarpa',
  'Polygala Lutea',
  'Glycyrrhiza Glabra',
  'Gymnocladus Dioicus',
  'Cercis Canadensis',
  'Copaifera Officinalis',
  'Cladrastis Kentukea',
  'Codoriocalyx Motorius',
  'Desmanthus Illinoensis',
  'Oenothera Rhombipetala',
  'Xanthocercis Zambesiaca',
  'Manihot Esculenta Subsp. Flabellifolia',
  'Solanum Acaule',
  'Acyrtus Rubiginosus',
  'Antigonia Capros',
  'Kadsura Heteroclita',
  'Apogon Cathetogrammus',
  'Helianthus Argophyllus',
  'Helianthus Debilis',
  'Helianthus Annuus Subsp. Texanus',
  'Helianthus Petiolaris',
  'Helianthus Bolanderi',
  'Helianthus Exilis',
  'Helianthus Annuus Subsp. Annuus',
  'Argentina Sp. Cur14063.g',
  'Atractosteus Spatula',
  'Xylaria Striata',
  'Manihot Esculenta Subsp. Esculenta',
  'Nilaparvata Lugens',
  'Echinochloa Glabrescens',
  'Channa Micropeltes',
  'Chaunax Pictus',
  'Chlorophthalmus Sp. Cur14065.g',
  'Cyclopterus Lumpus',
  'Jatropha Curcas',
  'Prunus Persica Var. Nucipersica',
  'Solanum Phureja',
  'Arachis Hypogaea',
  'Seed Metagenome',
  'Gigaspora Rosea',
  'Hirpicium Armerioides',
  'Gazania Krebsiana',
  'Arctotis Venusta',
  'Arctotis Gumbletonii',
  'Arctotheca Populifolia',
  'Ursinia Anthemoides',
  'Arctotis Fastuosa',
  'Galinsoga Parviflora',
  'Mutisia Ilicifolia',
  'Gaillardia Aristata',
  'Doronicum Grandiflorum',
  'Centaurea Pulcherrima',
  'Centaurea Phrygia Subsp. Pseudophrygia',
  'Centaurea Montana',
  'Centaurea Dealbata',
  'Centaurea Cyanoides',
  'Plectocephalus Americanus',
  'Arnica Chamissonis',
  'Tragopogon Porrifolius',
  'Sonchus Asper',
  'Scorzonera Hispanica',
  'Centaurea Macrocephala',
  'Ligularia Przewalskii',
  'Osteospermum Sinuatum',
  'Osteospermum Jucundum',
  'Steirodiscus Tagetes',
  'Melampodium Paludosum',
  'Senecio Vulgaris',
  'Jacobaea Abrotanifolia',
  'Othonna Arborescens',
  'Inula Racemosa',
  'Inula Ensifolia',
  'Doronicum Orientale',
  'Cynara Cardunculus Var. Scolymus',
  'Cosmos Sulphureus',
  'Buphthalmum Salicifolium',
  'Bidens Pilosa',
  'Ageratum Houstonianum',
  'Tussilago Farfara',
  'Taraxacum Officinale',
  'Inula Helenium',
  'Echinops Ritro',
  'Coreopsis Grandiflora',
  'Artemisia Absinthium',
  'Doronicum Caucasicum',
  'Tanacetum Balsamita',
  'Oncosiphon Africanus',
  'Lonas Annua',
  'Gazania Splendens',
  'Gazania Rigens',
  'Dahlia Pinnata',
  'Coreopsis Lanceolata',
  'Tanacetum Coccineum',
  'Mauranthemum Paludosum',
  'Leucanthemum Vulgare',
  'Tanacetum Cinerariifolium',
  'Leucanthemum Maximum',
  'Arctotis Scapigera',
  'Anacyclus Depressus',
  'Ageratum Mexicanum',
  'Achillea Ptarmica',
  'Achillea Filipendulina',
  'Senecio Magnificus',
  'Zinnia Violacea',
  'Gazania Hybrid Cultivar',
  'Centaurea Cyanus',
  'Xerochrysum Viscosum',
  'Waitzia Nitida',
  'Amblysperma Spathulata',
  'Olearia Lirata',
  'Xerochrysum Macranthum',
  'Brachyscome Iberidifolia',
  'Chromolaena Odorata',
  'Melampodium Leucanthum',
  'Engelmannia Peristenia',
  'Tetragonotheca Texana',
  'Amia Calva',
  'Gymnothorax Reevesii',
  'Gyrinocheilus Aymonieri',
  'Homatula Potanini',
  'Bos Grunniens X Bos Taurus',
  'Anomodon Attenuatus',
  'Ceratodon Purpureus',
  'Hedwigia Ciliata',
  'Thuidium Delicatulum',
  'Metzgeria Crassipilis',
  'Sphaerocarpos Texanus',
  'Pyramimonas Parkeae',
  'Monomastix Opisthostigma',
  'Klebsormidium Subtile',
  'Entransia Fimbriata',
  'Mougeotia',
  'Spirogyra Sp.',
  'Cosmarium Ochthodes',
  'Roya Obtusa',
  'Spirotaenia Minuta',
  'Bassia Scoparia',
  'Boehmeria Nivea',
  'Hibiscus Cannabinus',
  'Rosmarinus Officinalis',
  'Acorus Americanus',
  'Smilax Bona-nox',
  'Gnetum Montanum',
  'Polytrichum Commune',
  'Myotis Myotis',
  'Achillea Millefolium',
  'Xeranthemum Annuum',
  'Xerochrysum Bracteatum',
  'Tagetes Patula',
  'Schoenia Filifolia',
  'Gerbera Jamesonii',
  'Streptoglossa Macrocephala',
  'Senecio Pinnatifolius Var. Maritimus',
  'Senecio Pinnatifolius Var. Latilobus',
  'Ixodia Achillaeoides Subsp. Achillaeoides',
  'Marshallia Caespitosa',
  'Ambrosia Trifida',
  'Gaillardia Pulchella',
  'Guizotia Abyssinica',
  'Rudbeckia Hirta',
  'Echinacea Purpurea',
  'Callistephus Chinensis',
  'Cyttopsis Sp. Cur14111.g',
  'Dascyllus Trimaculatus',
  'Enneanectes Sp. Cur14108.g',
  'Epigonus Sp. Cur14046.g',
  'Rosulabryum Capillare',
  'Nothoceros Aenigmaticus',
  'Nothoceros Vincentianus',
  'Ricciocarpos Natans',
  'Nephroselmis Pyriformis',
  'Uronema',
  'Mesostigma Viride',
  'Chara Vulgaris',
  'Chaetosphaeridium Globosum',
  'Mesotaenium Endlicherianum',
  'Cylindrocystis Brebissonii',
  'Netrium Digitus',
  'Penium Margaritaceum',
  'Saruma Henryi',
  'Podophyllum Peltatum',
  'Larrea Tridentata',
  'Dioscorea Villosa',
  'Colchicum Autumnale',
  'Yucca Filamentosa',
  'Welwitschia Mirabilis',
  'Cycas Micholitzii',
  'Angiopteris Evecta',
  'Ophioglossum Petiolatum',
  'Sphagnum Lescurii',
  'Bazzania Trilobata',
  'Marchantia Emarginata',
  'Equetus Punctatus',
  'Erythrinus Erythrinus',
  'Eucinostomus Jonesii',
  'Evynnis Cardinalis',
  'Foetorepus Agassizii',
  'Gasteropelecus Sp. Gz2014122002',
  'Glossogobius Aureus',
  'Glyptothorax Sinensis',
  'Haemulon Flavolineatum',
  'Hemibagrus Guttatus',
  'Hemigrammus Bleheri',
  'Hepsetus Odoe',
  'Liobagrus Styani',
  'Lipogramma Evides',
  'Planiliza Haematocheila',
  'Lutjanus Fulviflamma',
  'Lutjanus Sebae',
  'Macrognathus Aculeatus',
  'Misgurnus Anguillicaudatus',
  'Mormyrus Tapirus',
  'Mugil Cephalus',
  'Nomeus Gronovii',
  'Osphronemus Goramy',
  'Ostracion Rhinorhynchos',
  'Polynemus Dubius',
  'Polypterus Bichir',
  'Polypterus Endlicherii',
  'Scomberomorus Regalis',
  'Siganus Guttatus',
  'Sinibotia Superciliaris',
  'Synodus Sp. Cur14055.g',
  'Thalassoma Bifasciatum',
  'Thayeria Boehlkei',
  'Tomicodon Sp. Cur14110.g',
  'Amphiprion Melanopus',
  'Siniperca Scherzeri',
  'Hymenopappus Tenuifolius',
  'Coreopsis Tinctoria',
  'Lindheimera Texana',
  'Liatris Spicata',
  'Parthenium Argentatum',
  'Cichorium Endivia',
  'Parthenium Integrifolium',
  'Cosmos Bipinnatus',
  'Tagetes Erecta',
  'Tithonia Rotundifolia',
  'Ratibida Columnifera',
  'Sanvitalia Procumbens',
  'Aubrieta X Cultorum',
  'Erysimum Cheiri',
  'Eruca Vesicaria Subsp. Sativa',
  'Iberis Amara',
  'Lobularia Maritima',
  'Malcolmia Maritima',
  'Matthiola Incana',
  'Raphanus Sativus',
  'Oryza Sativa Japonica Group X Oryza Sativa Indica Group',
  'Oryza Sativa Indica Group X Oryza Sativa Japonica Group',
  'Root Metagenome',
  'Meloidogyne Hapla',
  'Prunus Armeniaca',
  'Prunus Salicina',
  'Prunus Mume',
  'Prunus Cerasus',
  'Prunus Domestica',
  'Prunus Cerasifera',
  'Datnioides Microlepis',
  'Leucodon Brachypus',
  'Urochloa Fusca',
  'Paspalum Vaginatum',
  'Rhynchostegium Serrulatum',
  'Coleochaete Irregularis',
  'Fusarium Mangiferae',
  'Fusarium Proliferatum',
  'Fusarium Verticillioides 7600',
  'Coleochaete Scutata',
  'Chlorokybus Atmophyticus',
  'Ustilago Maydis',
  'Cylindrocystis Cushleckae',
  'Allamanda Cathartica',
  'Catharanthus Roseus',
  'Tanacetum Parthenium',
  'Disakisperma Dubium',
  'Panicum Coloratum',
  'Panicum Monticola',
  'Diplachne Fusca',
  'Axonopus Fissifolius',
  'Astrebla Pectinata',
  'Chloris Gayana',
  'Echinochloa Frumentacea',
  'Panicum Virgatum',
  'Panicum Antidotale',
  'Panicum Bisulcatum',
  'Triticum',
  'Aegilops Longissima',
  'Aegilops Speltoides',
  'Ginkgo Biloba',
  'Ephedra Sinica',
  'Taxus Baccata',
  'Phlegmariurus Squarrosus',
  'Digitaria Californica',
  'Panicum Hallii',
  'Sacciolepis Indica',
  'Torulaspora Delbrueckii',
  'Saccharomyces Paradoxus',
  'Saccharomyces Eubayanus',
  'Saccharomyces Kudriavzevii',
  'Cryptococcus Neoformans',
  'Saccharomyces',
  'Saccharomyces Cerevisiae T73',
  'Equisetum Diffusum',
  'Dendrochirus Zebra',
  'Bombyx Mandarina',
  'Saccharomyces Mikatae',
  'Naumovozyma Castellii',
  'Lachancea Kluyveri',
  'Kluyveromyces Lactis',
  'Lachancea Waltii',
  'Lachancea Thermotolerans',
  'Dugesia Japonica',
  'Zygosaccharomyces Rouxii',
  'Planococcus Citri',
  'Diaphorina Citri',
  'Musa Acuminata Subsp. Acuminata',
  'Scheffersomyces Stipitis',
  'Fusarium Oxysporum F. Sp. Cubense',
  'Cryptococcus Neoformans Var. Grubii',
  'Saccharomyces Cerevisiae X Saccharomyces Paradoxus',
  'Saccharomyces Cerevisiae X Saccharomyces Mikatae',
  'Saccharomyces Cerevisiae X Saccharomyces Bayanus',
  'Aphis Gossypii',
  'Aphis Glycines',
  'Caenorhabditis Nigoni',
  'Diodon Holocanthus',
  'Distichodus Sexfasciatus',
  'Apis Cerana',
  'Drepane Punctata',
  'Exyrias Puntang',
  'Vanderwaltozyma Polyspora',
  'Apis Mellifera Ligustica',
  'Nasonia Giraulti',
  'Oreochromis Mossambicus',
  'Aedes Albopictus',
  'Copadichromis Virginalis',
  'Dimidiochromis Kiwinge',
  'Diplotaxodon Limnothrissa',
  "Diplotaxodon Sp. 'similis'",
  'Lethrinops Gossei',
  'Petrotilapia Genalutea',
  'Eclectochromis Ornatus',
  'Rhamphochromis Longiceps',
  'Trematocranus Placodon',
  'Haplochromis Burtoni',
  'Anas Rubripes',
  'Apteryx Rowi',
  'Oxyura Jamaicensis',
  'Aythya Affinis',
  'Osteoglossum Bicirrhosum',
  'Acipenser Ruthenus X Huso Huso',
  'Pantodon Buchholzi',
  'Papyrocranus Afer',
  'Histrionicus Histrionicus',
  'Aix Sponsa',
  'Anopheles Merus',
  'Anopheles Gambiae X Anopheles Merus',
  'Lethenteron Camtschaticum',
  'Scyliorhinus Torazame',
  'Xenopus Tropicalis X Xenopus Laevis',
  'Columba Livia',
  'Oreochromis Niloticus Vulcani',
  'Lasius Flavus',
  'Lasius Niger',
  'Gerres Filamentosus',
  'Glossolepis Incisus',
  'Culex Pipiens Pallens',
  'Gallus Gallus Gallus',
  'Anopheles Coluzzii',
  'Anguilla Japonica',
  'Drosophila Hawaiiensis',
  'Drosophila Hemipeza',
  'Drosophila Heteroneura',
  'Drosophila Silvestris',
  'Abatus Agassizii',
  'Culex Pipiens Molestus',
  'Abatus Cordatus',
  'Allolobophora Chlorotica L1',
  'Allolobophora Chlorotica L2',
  'Allolobophora Chlorotica L4',
  'Aporrectodea Icterica',
  'Armadillidium Nasatum',
  'Armadillidium Vulgare',
  'Artemia Franciscana',
  'Artemia Salina',
  'Artemia Sinica',
  'Artemia Tibetiana',
  'Bostrycapulus Aculeatus',
  'Caenorhabditis Sp. 10 Jr-2014',
  'Camponotus Aethiops',
  'Camponotus Ligniperda',
  'Carcinus Aestuarii',
  'Chelonoidis Niger',
  'Crepidula Fornicata',
  'Crepidula Plana',
  'Culex Hortensis',
  'Culex Pipiens',
  'Culex Torrentium',
  'Cystodytes Dellechiajei',
  'Echinocardium Mediterraneum',
  'Echinocardium Cordatum',
  'Emys Orbicularis',
  'Eudyptes Filholi',
  'Eudyptes Chrysocome Moseleyi',
  'Eunicella Cavolinii',
  'Eunicella Verrucosa',
  'Halictus Scabiosae',
  'Hippocampus Guttulatus',
  'Hippocampus Hippocampus',
  'Hippocampus Kuda',
  'Leptogorgia Sarmentosa',
  'Lepus Granatensis',
  'Ramphogordius Lacteus',
  'Lineus Longissimus',
  'Lineus Ruber',
  'Liocarcinus Depurator',
  'Meleagris Gallopavo Silvestris',
  'Melitaea Didyma',
  'Mellicta Athalia',
  'Mellicta Parthenoides',
  'Messor Barbarus',
  'Microtus Arvalis',
  'Mytilus Californianus',
  'Mytilus Edulis',
  'Mytilus Galloprovincialis',
  'Mytilus Trossulus',
  'Necora Puber',
  'Ophioderma Longicauda',
  'Ostrea Chilensis',
  'Ostrea Edulis',
  'Drosophila Miranda',
  'Brachygenys Chrysargyreum',
  'Drosophila Sechellia X Drosophila Mauritiana',
  'Lepisosteus Platyrhincus',
  'Pachypanchax Sakaramyi',
  'Sabal Bermudana',
  'Pronotogrammus Martinicensis',
  'Selaginella Peruviana',
  'Selaginella Borealis',
  'Ephydra Hians',
  'Tetranychus Cinnabarinus',
  'Protopterus Aethiopicus',
  'Pterygoplichthys Pardalis',
  'Rhamphichthys Rostratus',
  'Sargocentron Rubrum',
  'Scarus Ghobban',
  'Scarus Iseri',
  'Terapon Jarbua',
  'Ostrea Stentina',
  'Coreoperca Whiteheadi',
  'Lepidogalaxias Salamandroides',
  'Galaxiella Nigrostriata',
  'Crassostrea Angulata',
  'Cyanistes Caeruleus',
  'Pectinaria Koreni',
  'Pheidole Pallidula',
  'Physella Acuta',
  'Sepia Officinalis',
  'Thymelicus Sylvestris',
  'Trachemys Scripta',
  'Messor Structor',
  'Myodes Glareolus',
  'Hyporhamphus Intermedius',
  'Liriomyza Trifolii',
  'Selaginella Rupestris',
  'Pecten Maximus',
  'Scorpaenopsis Cirrosa',
  'Physella Gyrina',
  'Reticulitermes Grassei',
  'Thymelicus Lineola',
  'Schizocosmus Abatoides',
  'Pygoscelis Papua',
  'Halictus Simplex',
  'Sepiella Japonica',
  'Vitis Quinquangularis',
  'Aotus Lemurinus',
  'Themira Minor',
  'Selaginella Braunii',
  'Phortica Variegata',
  'Rhodnius Robustus',
  'Reticulitermes Flavipes',
  'Reticulitermes Lucifugus',
  'Saimiri Sciureus',
  'Selaginella Tamariscina',
  'Crassostrea Gigas X Crassostrea Angulata',
  'Pristionchus Marianneae',
  'Pristionchus Aerivorus',
  'Pristionchus Mayeri',
  'Pristionchus Lheritieri',
  'Pristionchus Japonicus',
  'Pristionchus Elegans',
  'Neofusicoccum Parvum',
  'Micoletzkya Masseyi',
  'Lotmaria Passim',
  'Streptococcus Agalactiae',
  'Crithidia Fasciculata',
  'Anopheles Arabiensis',
  'Anopheles Quadriannulatus',
  'Urolepis Rufipes',
  'Trichomalopsis Sarcophagae',
  'Human Gut Metagenome',
  'Anser Cygnoides',
  'Phasianus Colchicus',
  'Pavo Cristatus',
  'Drosophila Arizonae X Drosophila Mojavensis',
  'Pristionchus Bucculentus',
  'Vitis Vinifera Subsp. Sylvestris',
  'Hormiphora Palmata',
  'Pleurobrachia Pileus',
  'Pleurobrachia Sp. C Lm-2017',
  'Mertensiidae Sp. Lm-2017',
  'Pleurobrachia Sp. A Lm-2017',
  'Bolinopsis Infundibulum',
  'Trifolium Repens',
  'Pristionchus Bulgaricus',
  'Pristionchus Triformis',
  'Pristionchus Quartusdecimus',
  'Pristionchus Pseudaerivorus',
  'Pristionchus Pauli',
  'Pristionchus Americanus',
  'Nasonia Vitripennis X Nasonia Giraulti',
  'Drosophila Yakuba X Drosophila Santomea',
  'Drosophila Obscura',
  'Aptenodytes Forsteri',
  'Salamandra Salamandra',
  'Tupinambis Teguixin',
  'Basiliscus Plumifrons',
  'Boa Constrictor',
  'Crocodylus Niloticus',
  'Iguana Iguana',
  'Drosophila Albomicans',
  'Drosophila Nasuta',
  'Andrena Camellia',
  'Hyphessobrycon Anisitsi',
  'Polypterus Senegalus',
  'Crocodylus Siamensis',
  'Daboia Siamensis',
  'Paramesotriton Hongkongensis',
  'Ichthyophis Bannanicus',
  'Acipenser Transmontanus',
  'Lepidosiren Paradoxa',
  'Pristionchus Clavus',
  'Pristionchus Brevicauda',
  'Deformed Wing Virus',
  'Anas Platyrhynchos X Cairina Moschata',
  'Cairina Moschata',
  'Bolinopsis Ashleyi',
  'Cestum Veneris',
  'Cydippida Sp. Uf-2017',
  'Lobata Sp. Uf-2017',
  'Ocyropsis Sp. Uf-2017',
  'Ctenophora Sp. Lm-2017',
  'Ocyropsis Crystallina',
  'Ocyropsis Crystallina Guttata',
  'Eurhamphaea Vexilligera',
  'Cydippida Sp. Lm-2017',
  'Beroe Forskalii',
  'Beroe Ovata',
  'Mycobacterium Bovis Af2122/97',
  'Pleurobrachia Sp. B Lm-2017',
  'Gasterosteus Nipponicus',
  'Gasterosteus Nipponicus X Gasterosteus Aculeatus',
  'Erpetoichthys Calabaricus',
  'Pristionchus Uniformis'
]
