export const NOTIFICATION_TYPES = {
  basicInfo: [''],
  manageResources: ['MATERIAL_ADDED', 'MATERIAL_ARCHIVED', 'MATERIAL_DELETED'],
  requests: [
    'MATERIAL_REQUEST_SHARER_ASSIGNED_NEW',
    'MATERIAL_REQUEST_SHARER_RECEIVED',
    'MATERIAL_REQUEST_SHARER_ASSIGNED',
    'MATERIAL_REQUEST_SHARER_ASSIGNMENT',
    'MATERIAL_REQUEST_SHARER_APPROVED',
    'MATERIAL_REQUEST_SHARER_REJECTED',
    'MATERIAL_REQUEST_SHARER_CANCELLED',
    'MATERIAL_REQUEST_SHARER_RECEIVED_MTA',
    'MATERIAL_REQUEST_SHARER_RECEIVED_INFO',
    'MATERIAL_REQUEST_SHARER_EXECUTED_MTA',
    'MATERIAL_REQUEST_SHARER_IN_FULFILLMENT',
    'MATERIAL_REQUEST_SHARER_FULFILLED',
    'MATERIAL_REQUEST_SHARER_VERIFIED',
    'MATERIAL_REQUEST_ISSUE_SHARER_REPORTED',
    'MATERIAL_REQUEST_REQUESTER_ACCEPTED',
    'MATERIAL_REQUEST_REQUESTER_IN_FULFILLMENT',
    'MATERIAL_REQUEST_REQUESTER_EXECUTED_MTA',
    'MATERIAL_REQUEST_REQUESTER_FULFILLED',
    'MATERIAL_REQUEST_REQUESTER_REJECTED',
    'MATERIAL_REQUEST_REQUESTER_ESCALATED'
  ],
  teams: [
    'ORGANIZATION_NEW_MEMBER',
    'ORGANIZATION_BECAME_OWNER',
    'ORGANIZATION_NEW_OWNER',
    'ORGANIZATION_MEMBER_LEFT',
    'ORGANIZATION_NEW_GRANT',
    'ORGANIZATION_INVITE'
  ]
}
