export const fakeSearchMaterialsResponse = {
  count: 17,
  next: null,
  previous: null,
  facets: {
    has_publication: { '1': 15, '0': 2 },
    'contact_user.published_name': {
      'Dr. Prim Proffer': 9,
      'Dr. Postsworth Doktor': 6,
      'Dr. Secundus Profarius': 2
    },
    has_pre_print: { '1': 13, '0': 4 },
    category: {
      DATASET: 4,
      MODEL_ORGANISM: 4,
      CELL_LINE: 2,
      OTHER: 2,
      PLASMID: 2,
      PROTOCOL: 2,
      PDX: 1
    },
    'contact_user.email': {
      'pprof@havard.edu': 9,
      'pdoc@harvard.edu': 6,
      'secprof@harvard.edu': 2
    },
    organism: { 'danio rerio': 9, 'mus musculus': 4 }
  },
  results: [
    {
      id: 1,
      category: 'PLASMID',
      title: 'Melanoma Reduction Plasmid',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:44.916153+00:00',
      updated_at: '2020-05-06T20:45:44.916180+00:00',
      organism: ['Danio rerio', 'Mus musculus'],
      has_publication: true,
      has_pre_print: false,
      additional_info: '',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: 'Expression Analysis of Zebrafish Melanoma',
      pre_print_doi: '',
      pre_print_title: '',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        purpose: 'Reduces melanoma growth rate',
        copy_number: 'High',
        plasmid_name: 'pGP1871',
        plasmid_type: 'Encodes one insert',
        growth_strain: 'Escherichia coli',
        sequence_maps: [
          {
            map_url: 'https://bucket-name.s3.region.amazonaws.com/keyname',
            sequence:
              'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCT GTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGGGCTGG CTTAACTATGCGGCATCAGAGCAGATTGTACTGAGAGTGCACCATATGGTACCAAATTTATTGATGGATC AATTTAAAGAGTTTTAATCTGGGTGTTATGAGTTCCTTGGGCCTATTGTTTGCCTGAACCCTGTGGGGAC TGGCTCATCAGCAGAATTATTCATGGAGGAATTTGCTAGGTTTTACCTTGGCTCTCTAGCTTGGGACATT TTGTTTCTTCCTTAAATCCTTATTGCAACCGTCCAGCTACCAGGTAGGTATATTGCCTTGTAAGTGCTGG TACAGTTTGCCTTATTTATATTCCACTGCTTCTCAGGGATTAACATCTGCTCGTGCAGCTGAGATCCTGG CGCGAGATGGTCCCAACGCCCTCACTCCCCCTCCCACTACTCCTGAATGGATCAAGTTTTGTCGGCAGCT CTTTGGGGGGTTCTCAATGTTACTGTGGATTGGAGCGATTCTTTGTTTCTTGGCTTATAGCATCAGAGCT GCTACAGAAGAGGAACCTCAAAACGATGACGTGAGTTCTGTAATTCAGCATATCGATTTGTAGTACACAT CAGATATCTTCTCCGTCTTTGTCTCCCACTTCTTCTCAATTACCACTCATTACTTAATGGTTATGAACTC ATTACTTAATGGTTATGAACAGCTGTTGCCTTCAAGGCTCATCCATTCTTCCTTCGTTTCCATTTCCTCT CTCTACCACCCACGTTGTAGATGCTCTTACAAGTGGGATGCCCACCTGCATGTGCTGCTGTGAGCAGGCA GCTCTGCTCAGGCCCCGGCCGCCACCCACTGGATGGCAGAGCACAGCGATTCATGTTGGCACATCCACCT GTCCAGAAATGCTTGGTGGCCATTCTTCAAAATCCACAAGTTGGTTGAAAAACAATCTTTGTTTTATAAA GCAGGAGAAACTGATGCATCTAGAACCTTTCCAAACGTCCAGTTAGTGATCAAGTGTTGGTGTGCCTGAC TCCATTTCTGACCCTTCCTGTGTGGTCTTTAGAAGGGAATTCTGCATTAATGAATCGGCCAACGCGCGGG GAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGG CTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAG GAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTT CCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACA GGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGC TTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTA TCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGC TGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAG CCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAA CTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGA GTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGA TTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAA CGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAAT TAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAA TCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTA GATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCA CCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTT TATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTT GCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGC TCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCG GTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAA TTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGA GAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCA GAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTT GAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTT TCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAA TACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACAT ATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGAC GTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCCCTTTCGTC'
          }
        ],
        cloning_method: 'Unknown',
        biosafety_level: '2',
        gene_insert_name: ['Danio rerio', 'Dani devrito'],
        relevant_mutations: 'Skin regrowth sequence modified',
        growth_temp_celsius: '32.0',
        primary_vector_type: 'Bacterial Expression',
        bacterial_resistance: 'Kanamycin',
        plasmid_backbone_name: 'pSB1A30',
        'Number of Availible Samples': '20'
      },
      imported: false,
      import_source: null
    },
    {
      id: 2,
      category: 'PROTOCOL',
      title: 'Allele Extraction Protocol',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:44.971224+00:00',
      updated_at: '2020-05-06T20:45:44.971251+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: false,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title: 'Extraction of t-type alleles from zebrafish samples',
      pre_print_doi: '',
      pre_print_title: '',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        description:
          'A protocol to retrieve t-type alleles relibably and without damage.',
        protocol_name: 'Extraction of t-type alleles from zebrafish samples'
      },
      imported: false,
      import_source: null
    },
    {
      id: 3,
      category: 'MODEL_ORGANISM',
      title: 'Zebrafish Model Organism',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.007121+00:00',
      updated_at: '2020-05-06T20:45:45.007146+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: false,
      additional_info: '',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title: '',
      pre_print_doi: '',
      pre_print_title: '',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        genotype: 'TTdDsS',
        zygosity: 'Heterozygous',
        description:
          'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma.',
        strain_name: 'Domestica salvis',
        construct_details: 'The dominant gene is represented in this sample.',
        genetic_background: 'TTdDss',
        number_availible_models: '20'
      },
      imported: false,
      import_source: null
    },
    {
      id: 4,
      category: 'MODEL_ORGANISM',
      title: 'Mouse Model Organism',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.044919+00:00',
      updated_at: '2020-05-06T20:45:45.044946+00:00',
      organism: ['Mus musculus'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title:
        'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Morphology',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        genotype: 'TTdDsS',
        zygosity: 'Heterozygous',
        description:
          'Investigation of expression differences between skin and melanomas from a house mouse.',
        strain_name: 'Sylvaticus',
        construct_details: 'The dominant gene is represented in this sample.',
        genetic_background: 'TTdDss',
        number_availible_models: '20'
      },
      imported: false,
      import_source: null
    },
    {
      id: 5,
      category: 'OTHER',
      title: 'Stone Tablet (Other)',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.083242+00:00',
      updated_at: '2020-05-06T20:45:45.083266+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This tablet was co-authored by Postworth Docktor.',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: 'The Ten Commandments',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'The Six and a Half Commandments',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {},
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        title: 'The Ten Commandments',
        description:
          'Given to me by an old man who said to "Let my research go". He then parted my hair by raising his staff and left.',
        resource_type: 'Stone Tablet'
      },
      imported: false,
      import_source: null
    },
    {
      id: 6,
      category: 'CELL_LINE',
      title: 'Zebrafish Cell Line',
      url: '',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.117405+00:00',
      updated_at: '2020-05-06T20:45:45.117432+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: false,
      additional_info: '',
      contact_name: '',
      contact_email: '',
      publication_title: '',
      pre_print_doi: '',
      pre_print_title: '',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Secundus',
        last_name: 'Profarius',
        published_name: 'Dr. Secundus Profarius',
        email: 'secprof@harvard.edu'
      },
      shipping_requirements: {},
      organization: { name: 'SecondaryProfOrg', id: 4 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        age: 'Four Months',
        sex: 'Male',
        disease: 'Affymetrix Zebrafish Genome Array',
        cell_type: 'Microarray',
        ethnicity: 'N/A',
        str_profile:
          'Amelogenin: X Y\nCSF1PO: 11\nD13S317: 8, 14\nD16S539: 9, 11\nD5S818: 11, 13\nD7S820: 10\nTH01: 6, 9.3\nTPOX: 9, 12\nvWA: 16, 17',
        subculturing: 'Methanol',
        growth_medium: 'Ethanol',
        cell_line_name: 'A549',
        passage_number: '21430780',
        storage_medium: 'Liquid nitrogen vapor phase',
        biosafety_level: '3',
        cryopreservation: 'Liquid nitrogen',
        tissue_histology: 'Brain Tumor',
        culture_conditions: 'Reproducing at a swift rate',
        population_doubling_time: '20 Hours',
        number_availible_cell_lines: '20'
      },
      imported: false,
      import_source: null
    },
    {
      id: 7,
      category: 'DATASET',
      title: 'Zebrafish Dataset',
      url: '',
      pubmed_id: '',
      created_at: '2020-05-06T20:45:45.157309+00:00',
      updated_at: '2020-05-06T20:45:45.157333+00:00',
      organism: ['Danio rerio'],
      has_publication: false,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: '',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {
        filename: 'PrimaryLabMTA.pdf',
        description: 'The MTA used by PrimaryLab.',
        s3_bucket: 'bucket-name',
        s3_key: 'keyname',
        download_url: 'https://s3.amazonaws.com/bucket-name/keyname',
        created_at: '2020-05-06T20:45:44.887972+00:00',
        updated_at: '2020-05-06T20:45:44.888002+00:00'
      },
      additional_metadata: {
        title: 'Zebrafish Analyis',
        platform: 'Amazon s3 Database',
        study_id: 'phs000328.v2.p1',
        technology: 'R-readable array',
        description: 'Data collected from genetically modified zebrafish.',
        study_id_type: 'dbgap_study_accession',
        number_samples: '15'
      },
      imported: false,
      import_source: null
    },
    {
      id: 8,
      category: 'PDX',
      title: 'Zebrafish PDX',
      url: '',
      pubmed_id: '',
      created_at: '2020-05-06T20:45:45.189997+00:00',
      updated_at: '2020-05-06T20:45:45.190020+00:00',
      organism: ['Danio rerio', 'Mus musculus'],
      has_publication: false,
      has_pre_print: true,
      additional_info: 'This tablet was co-authored by Postworth Docktor.',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: 'Grafting to Zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Preliminary research on Grafting to Zebrafish',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        age: '15',
        gender: 'Male',
        pdx_id: '81983924',
        lag_time: 'Three months',
        diagnosis: 'Stage 4 Lymphoma',
        ethnicity: 'Hispanic',
        tumor_type: 'Malignant',
        tumor_grade: 'AJCC IV',
        tumor_omics: 'Sample #194982984, mouse',
        disease_stage: '1',
        model_organism: 'Danio rerio',
        virology_status: 'Malignant tumor',
        consent_to_share: false,
        engraftment_time: 'Four days',
        specific_markers: 'Circulating marker',
        tissue_histology: 'Cancerous',
        treatment_passage: 'Daily glass of milk',
        tumor_preparation: 'Removed and preserved',
        tumor_sample_type: 'Biopsy',
        submitter_tumor_id: '92739492',
        treatment_response: 'Positive',
        is_strain_immunized: 'Yes',
        animal_health_status: 'Good',
        is_not_of_EVB_origin: 'Yes',
        metastases_in_strain: 'Yes',
        submitter_patient_id: '18849839',
        type_of_humanization: 'Chimeric',
        goverance_restriction: 'None',
        specimen_tumor_tissue: 'Lung',
        current_treatment_drug: 'Anastrozole',
        pdx_model_availability: 'Availible',
        injection_type_and_site: 'Immediate, left thigh',
        is_passage_QA_performed: 'Yes',
        model_strain_and_source: 'Strain 2, from Croatia',
        number_availible_models: '20',
        primary_tissue_of_origin: 'Lung',
        prior_treatment_protocol: '10 mg Anastrozole daily',
        is_from_untreated_patient: 'No',
        treatment_for_engraftment: 'Sedation',
        current_treatment_protocol: '30 mg Anastrozole daily',
        existing_model_explaination: 'Sublining to do further analysis',
        response_to_prior_treatment: 'No response',
        response_to_standard_of_care: 'Positive',
        tumor_characterization_technology: 'Centrifuge'
      },
      imported: false,
      import_source: null
    },
    {
      id: 9,
      category: 'DATASET',
      title: 'Imported GEO Dataset',
      url: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE31712',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.220966+00:00',
      updated_at: '2020-05-06T20:45:45.220992+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      contact_name: '',
      contact_email: '',
      publication_title: 'Data collected from genetically modified zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {},
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        title: 'Imported Zebrafish Analyis',
        platform: 'Amazon s3 Database',
        study_id: 'GSE24528',
        technology: 'R-readable array',
        description: 'Data collected from genetically modified zebrafish.',
        study_id_type: 'accession_id',
        number_samples: '15'
      },
      imported: true,
      import_source: 'GEO'
    },
    {
      id: 10,
      category: 'DATASET',
      title: 'Imported SRA Dataset',
      url: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE37165',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.249438+00:00',
      updated_at: '2020-05-06T20:45:45.249472+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      contact_name: null,
      contact_email: 'pprof@harvard.edu',
      publication_title: 'Data collected from genetically modified zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        title: 'GEO Zebrafish Analysis',
        description:
          'This dataset has interesting implications for future research.',
        contact_name: 'Prim Proffer',
        embargo_date: '2020-01-30',
        number_samples: '15'
      },
      imported: true,
      import_source: 'SRA'
    },
    {
      id: 11,
      category: 'DATASET',
      title: 'Imported dbGaP Dataset',
      url:
        'https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000328.v2.p1',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.294699+00:00',
      updated_at: '2020-05-06T20:45:45.294726+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: 'Data collected from genetically modified zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        title: 'GEO Zebrafish Analysis',
        accession: 'phs000328.v2.p1',
        description:
          'This dataset has interesting implications for future research.',
        number_samples: '15'
      },
      imported: true,
      import_source: 'DBGAP'
    },
    {
      id: 12,
      category: 'PROTOCOL',
      title: 'Imported Protocol',
      url:
        'https://www.protocols.io/view/labyrinthulomycete-dna-extraction-protocol-n83dhyn',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.345977+00:00',
      updated_at: '2020-05-06T20:45:45.346004+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title: 'Extraction of t-type alleles from zebrafish samples',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Extraction',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        abstract:
          'A protocol to retrieve t-type alleles relibably and without damage.',
        protocol_name: 'Extraction of t-type alleles from zebrafish samples'
      },
      imported: true,
      import_source: 'PROTOCOLS_IO'
    },
    {
      id: 13,
      category: 'PLASMID',
      title: 'Imported AddGene Melanoma Reduction Plasmid',
      url: 'https://www.addgene.org/53246/',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.387183+00:00',
      updated_at: '2020-05-06T20:45:45.387210+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: null,
      contact_email: 'pdoc@harvard.edu',
      publication_title: 'Imported Plasmid',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Plasmids',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        description: 'Reduces melanoma growth rate',
        contact_name: 'Postworth Docktor',
        plasmid_name: 'pGP1871',
        relevant_mutations: 'Biofloresence',
        insert_delete_genes:
          'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCT'
      },
      imported: true,
      import_source: 'ADDGENE'
    },
    {
      id: 14,
      category: 'MODEL_ORGANISM',
      title: 'Jackson Labs Imported Mouse Model Organism',
      url: 'https://www.jax.org/strain/006933',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.422737+00:00',
      updated_at: '2020-05-06T20:45:45.422763+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title:
        'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Morphology',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        description:
          'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma.',
        strain_name: 'Domestica salvis'
      },
      imported: true,
      import_source: 'JACKSON_LABS'
    },
    {
      id: 15,
      category: 'CELL_LINE',
      title: 'ATCC Imported Zebrafish Cell Line',
      url: 'https://www.atcc.org/products/all/CCL-185.aspx#generalinformation',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.453015+00:00',
      updated_at: '2020-05-06T20:45:45.453041+00:00',
      organism: ['Danio rerio'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      contact_name: 'Secundus Profarius',
      contact_email: 'secprof@harvard.edu',
      publication_title: 'Cell Line from Zebrafish Sample',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Preliminary Research',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Secundus',
        last_name: 'Profarius',
        published_name: 'Dr. Secundus Profarius',
        email: 'secprof@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: false,
        accepts_shipping_code: false,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'None. Free yourself!',
        created_at: '2020-05-06T20:45:44.672841+00:00',
        updated_at: '2020-05-06T20:45:44.672871+00:00'
      },
      organization: { name: 'SecondaryProfOrg', id: 4 },
      mta_attachment: {},
      additional_metadata: {
        age: 'Four Months',
        sex: 'Male',
        tissue: '15',
        disease: 'Affymetrix Zebrafish Genome Array',
        cell_type: 'Microarray',
        ethnicity: 'N/A',
        cell_line_name: 'A549',
        number_availible_cell_lines: '20'
      },
      imported: true,
      import_source: 'ATCC'
    },
    {
      id: 16,
      category: 'MODEL_ORGANISM',
      title: 'ZIRC Imported Zebrafish Model Organism',
      url: 'http://zfin.org/ZDB-GENO-100413-1',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.489724+00:00',
      updated_at: '2020-05-06T20:45:45.489745+00:00',
      organism: ['Mus musculus'],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This paper was co-authored by Prim Proffer.',
      contact_name: 'Postworth Docktor',
      contact_email: 'pdoc@harvard.edu',
      publication_title:
        'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Morphology',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Postsworth',
        last_name: 'Doktor',
        published_name: 'Dr. Postsworth Doktor',
        email: 'pdoc@harvard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        genotype: 'TTdDsS',
        description:
          'Investigation of expression differences between skin and melanomas from a house mouse.',
        strain_name: 'Sylvaticus',
        genetic_background: 'TTdDss'
      },
      imported: true,
      import_source: 'ZIRC'
    },
    {
      id: 17,
      category: 'OTHER',
      title: 'Imported Stone Tablet (Other)',
      url: 'https://www.ncbi.nlm.nih.gov/pubmed/32223680',
      pubmed_id: '32223680',
      created_at: '2020-05-06T20:45:45.519804+00:00',
      updated_at: '2020-05-06T20:45:45.519829+00:00',
      organism: [],
      has_publication: true,
      has_pre_print: true,
      additional_info: 'This tablet was co-authored by Postworth Docktor.',
      contact_name: 'Prim Proffer',
      contact_email: 'pprof@harvard.edu',
      publication_title: 'The Ten Commandments',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'The Six and a Half Commandments',
      embargo_date: '2020-01-30',
      contact_user: {
        first_name: 'Prim',
        last_name: 'Proffer',
        published_name: 'Dr. Prim Proffer',
        email: 'pprof@havard.edu'
      },
      shipping_requirements: {
        needs_shipping_address: true,
        needs_payment: true,
        accepts_shipping_code: true,
        accepts_reimbursement: false,
        accepts_other_payment_methods: false,
        restrictions: 'Only ships within the greater Hanover area.',
        created_at: '2020-05-06T20:45:44.666439+00:00',
        updated_at: '2020-05-06T20:45:44.666480+00:00'
      },
      organization: { name: 'PrimaryLab', id: 1 },
      mta_attachment: {},
      additional_metadata: {
        title: 'The Ten Commandments',
        description:
          'Given to me by an old man who said to "Let my research go". He then parted my hair by raising his staff and left.',
        resource_type: 'Stone Tablet'
      },
      imported: true,
      import_source: 'OTHER'
    }
  ]
}

export default {
  fakeSearchMaterialsResponse
}
