export const fakeSearchMaterialsResponse = {
  count: 17,
  next: 'http://localhost:8000/v1/materials/?format=json&page=2',
  previous: null,
  results: [
    {
      id: 1,
      category: 'PLASMID',
      title: 'Melanoma Reduction Plasmid',
      url: '',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        purpose: 'Reduces melanoma growth rate',
        copy_number: 'High',
        plasmid_name: 'pGP1871',
        plasmid_type: 'Encodes one insert',
        growth_strain: 'Escherichia coli',
        sequence_maps: [
          {
            map_url: 'https://bucket-name.s3.region.amazonaws.com/keyname',
            sequence:
              'TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGACGGTCACAGCTTGTCT GTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGGGCGCGTCAGCGGGTGTTGGCGGGTGTCGGGGCTGG CTTAACTATGCGGCATCAGAGCAGATTGTACTGAGAGTGCACCATATGGTACCAAATTTATTGATGGATC AATTTAAAGAGTTTTAATCTGGGTGTTATGAGTTCCTTGGGCCTATTGTTTGCCTGAACCCTGTGGGGAC TGGCTCATCAGCAGAATTATTCATGGAGGAATTTGCTAGGTTTTACCTTGGCTCTCTAGCTTGGGACATT TTGTTTCTTCCTTAAATCCTTATTGCAACCGTCCAGCTACCAGGTAGGTATATTGCCTTGTAAGTGCTGG TACAGTTTGCCTTATTTATATTCCACTGCTTCTCAGGGATTAACATCTGCTCGTGCAGCTGAGATCCTGG CGCGAGATGGTCCCAACGCCCTCACTCCCCCTCCCACTACTCCTGAATGGATCAAGTTTTGTCGGCAGCT CTTTGGGGGGTTCTCAATGTTACTGTGGATTGGAGCGATTCTTTGTTTCTTGGCTTATAGCATCAGAGCT GCTACAGAAGAGGAACCTCAAAACGATGACGTGAGTTCTGTAATTCAGCATATCGATTTGTAGTACACAT CAGATATCTTCTCCGTCTTTGTCTCCCACTTCTTCTCAATTACCACTCATTACTTAATGGTTATGAACTC ATTACTTAATGGTTATGAACAGCTGTTGCCTTCAAGGCTCATCCATTCTTCCTTCGTTTCCATTTCCTCT CTCTACCACCCACGTTGTAGATGCTCTTACAAGTGGGATGCCCACCTGCATGTGCTGCTGTGAGCAGGCA GCTCTGCTCAGGCCCCGGCCGCCACCCACTGGATGGCAGAGCACAGCGATTCATGTTGGCACATCCACCT GTCCAGAAATGCTTGGTGGCCATTCTTCAAAATCCACAAGTTGGTTGAAAAACAATCTTTGTTTTATAAA GCAGGAGAAACTGATGCATCTAGAACCTTTCCAAACGTCCAGTTAGTGATCAAGTGTTGGTGTGCCTGAC TCCATTTCTGACCCTTCCTGTGTGGTCTTTAGAAGGGAATTCTGCATTAATGAATCGGCCAACGCGCGGG GAGAGGCGGTTTGCGTATTGGGCGCTCTTCCGCTTCCTCGCTCACTGACTCGCTGCGCTCGGTCGTTCGG CTGCGGCGAGCGGTATCAGCTCACTCAAAGGCGGTAATACGGTTATCCACAGAATCAGGGGATAACGCAG GAAAGAACATGTGAGCAAAAGGCCAGCAAAAGGCCAGGAACCGTAAAAAGGCCGCGTTGCTGGCGTTTTT CCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACA GGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGC TTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTA TCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGC TGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAG CCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAA CTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGA GTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGA TTACGCGCAGAAAAAAAGGATCTCAAGAAGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAA CGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAAT TAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAA TCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTA GATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGACCCACGCTCA CCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTT TATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTT GCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGC TCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCG GTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAA TTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGA GAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCA GAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTT GAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTT TCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAA TACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACAT ATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACATTTCCCCGAAAAGTGCCACCTGAC GTCTAAGAAACCATTATTATCATGACATTAACCTATAAAAATAGGCGTATCACGAGGCCCTTTCGTC'
          }
        ],
        cloning_method: 'Unknown',
        biosafety_level: '2',
        gene_insert_name: ['Danio rerio', 'Dani devrito'],
        relevant_mutations: 'Skin regrowth sequence modified',
        growth_temp_celsius: '32.0',
        primary_vector_type: 'Bacterial Expression',
        bacterial_resistance: 'Kanamycin',
        plasmid_backbone_name: 'pSB1A30',
        'Number of Availible Samples': '20'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: false,
      needs_abstract: false,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [1],
      organisms: ['Danio rerio', 'Mus musculus'],
      publication_title: 'Expression Analysis of Zebrafish Melanoma',
      pre_print_doi: '',
      pre_print_title: '',
      citation:
        'Proffer, Prim. "Expression Analysis of Zebrafish Melanoma". March 15, 2020.',
      additional_info: '',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:06+0000',
      updated_at: '2020-08-15T22:01:06+0000'
    },
    {
      id: 2,
      category: 'PROTOCOL',
      title: 'Allele Extraction Protocol',
      url: '',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        description:
          'A protocol to retrieve t-type alleles relibably and without damage.',
        protocol_name: 'Extraction of t-type alleles from zebrafish samples'
      },
      contact_user: '20000000-a55d-42b7-b53e-056956e18b8c',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: false,
      needs_abstract: true,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [1],
      organisms: null,
      publication_title: 'Extraction of t-type alleles from zebrafish samples',
      pre_print_doi: '',
      pre_print_title: '',
      citation: '',
      additional_info: 'This paper was co-authored by Prim Proffer.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:07+0000',
      updated_at: '2020-08-15T22:01:07+0000'
    },
    {
      id: 3,
      category: 'MODEL_ORGANISM',
      title: 'Zebrafish Model Organism',
      url: '',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        genotype: 'TTdDsS',
        zygosity: 'Heterozygous',
        description:
          'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma.',
        strain_name: 'Domestica salvis',
        construct_details: 'The dominant gene is represented in this sample.',
        genetic_background: 'TTdDss',
        number_availible_models: '20'
      },
      contact_user: '20000000-a55d-42b7-b53e-056956e18b8c',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: true,
      needs_abstract: true,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [1],
      organisms: ['Danio rerio'],
      publication_title: '',
      pre_print_doi: '',
      pre_print_title: '',
      citation: '',
      additional_info: '',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:07+0000',
      updated_at: '2020-08-15T22:01:07+0000'
    },
    {
      id: 4,
      category: 'MODEL_ORGANISM',
      title: 'Mouse Model Organism',
      url: '',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        genotype: 'TTdDsS',
        zygosity: 'Heterozygous',
        description:
          'Investigation of expression differences between skin and melanomas from a house mouse.',
        strain_name: 'Sylvaticus',
        construct_details: 'The dominant gene is represented in this sample.',
        genetic_background: 'TTdDss',
        number_availible_models: '20'
      },
      contact_user: '20000000-a55d-42b7-b53e-056956e18b8c',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: false,
      needs_abstract: true,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [1],
      organisms: ['Mus musculus'],
      publication_title:
        'Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Initial Research on Zebrafish Morphology',
      citation:
        'Docktor, Postworth. "Investigation of expression differences between skin and melanomas from a transgenic BRAFV600E zebrafish model of melanoma.". March 15, 2020.',
      additional_info: 'This paper was co-authored by Prim Proffer.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:07+0000',
      updated_at: '2020-08-15T22:01:07+0000'
    },
    {
      id: 5,
      category: 'OTHER',
      title: 'Stone Tablet (Other)',
      url: '',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        title: 'The Ten Commandments',
        description:
          'Given to me by an old man who said to "Let my research go". He then parted my hair by raising his staff and left.',
        resource_type: 'Stone Tablet'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: false,
      needs_abstract: false,
      imported: false,
      shipping_requirements: null,
      import_source: null,
      grants: [2],
      organisms: null,
      publication_title: 'The Ten Commandments',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'The Six and a Half Commandments',
      citation: 'Proffer, Prim. "The Old Testament". March 15, 2020.',
      additional_info: 'This tablet was co-authored by Postworth Docktor.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:07+0000',
      updated_at: '2020-08-15T22:01:07+0000'
    },
    {
      id: 6,
      category: 'CELL_LINE',
      title: 'Zebrafish Cell Line',
      url: '',
      organization: 4,
      pubmed_id: '32223680',
      additional_metadata: {
        age: 'Four Months',
        sex: 'Male',
        disease: 'Affymetrix Zebrafish Genome Array',
        cell_type: 'Microarray',
        ethnicity: 'N/A',
        str_profile:
          'Amelogenin: X Y\nCSF1PO: 11\nD13S317: 8, 14\nD16S539: 9, 11\nD5S818: 11, 13\nD7S820: 10\nTH01: 6, 9.3\nTPOX: 9, 12\nvWA: 16, 17',
        subculturing: 'Methanol',
        growth_medium: 'Ethanol',
        cell_line_name: 'A549',
        passage_number: '21430780',
        storage_medium: 'Liquid nitrogen vapor phase',
        biosafety_level: '3',
        cryopreservation: 'Liquid nitrogen',
        tissue_histology: 'Brain Tumor',
        culture_conditions: 'Reproducing at a swift rate',
        population_doubling_time: '20 Hours',
        number_availible_cell_lines: '20'
      },
      contact_user: '30000000-231f-4dc8-bbfa-02bccfb0372c',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: true,
      needs_abstract: true,
      imported: false,
      shipping_requirements: null,
      import_source: null,
      grants: [2],
      organisms: ['Danio rerio'],
      publication_title: '',
      pre_print_doi: '',
      pre_print_title: '',
      citation: '',
      additional_info: '',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:07+0000',
      updated_at: '2020-08-15T22:01:07+0000'
    },
    {
      id: 7,
      category: 'DATASET',
      title: 'Zebrafish Dataset',
      url: '',
      organization: 1,
      pubmed_id: '',
      additional_metadata: {
        title: 'Zebrafish Analyis',
        platform: 'Amazon s3 Database',
        technology: 'R-readable array',
        description: 'Data collected from genetically modified zebrafish.',
        accession_code: 'phs000328.v2.p1',
        number_samples: '15'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: 1,
      needs_mta: true,
      needs_irb: false,
      needs_abstract: false,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [2],
      organisms: ['Danio rerio'],
      publication_title: '',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      citation: '',
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:08+0000',
      updated_at: '2020-08-15T22:01:08+0000'
    },
    {
      id: 8,
      category: 'PDX',
      title: 'Zebrafish PDX',
      url: '',
      organization: 1,
      pubmed_id: '',
      additional_metadata: {
        age: '15',
        gender: 'Male',
        pdx_id: '81983924',
        lag_time: 'Three months',
        diagnosis: 'Stage 4 Lymphoma',
        ethnicity: 'Hispanic',
        tumor_type: 'Malignant',
        tumor_grade: 'AJCC IV',
        tumor_omics: 'Sample #194982984, mouse',
        disease_stage: '1',
        model_organism: 'Danio rerio',
        virology_status: 'Malignant tumor',
        consent_to_share: false,
        engraftment_time: 'Four days',
        specific_markers: 'Circulating marker',
        tissue_histology: 'Cancerous',
        treatment_passage: 'Daily glass of milk',
        tumor_preparation: 'Removed and preserved',
        tumor_sample_type: 'Biopsy',
        submitter_tumor_id: '92739492',
        treatment_response: 'Positive',
        is_strain_immunized: 'Yes',
        animal_health_status: 'Good',
        is_not_of_EVB_origin: 'Yes',
        metastases_in_strain: 'Yes',
        submitter_patient_id: '18849839',
        type_of_humanization: 'Chimeric',
        goverance_restriction: 'None',
        specimen_tumor_tissue: 'Lung',
        current_treatment_drug: 'Anastrozole',
        pdx_model_availability: 'Availible',
        injection_type_and_site: 'Immediate, left thigh',
        is_passage_QA_performed: 'Yes',
        model_strain_and_source: 'Strain 2, from Croatia',
        number_availible_models: '20',
        primary_tissue_of_origin: 'Lung',
        prior_treatment_protocol: '10 mg Anastrozole daily',
        is_from_untreated_patient: 'No',
        treatment_for_engraftment: 'Sedation',
        current_treatment_protocol: '30 mg Anastrozole daily',
        existing_model_explaination: 'Sublining to do further analysis',
        response_to_prior_treatment: 'No response',
        response_to_standard_of_care: 'Positive',
        tumor_characterization_technology: 'Centrifuge'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: null,
      needs_mta: false,
      needs_irb: true,
      needs_abstract: true,
      imported: false,
      shipping_requirements: 1,
      import_source: null,
      grants: [2],
      organisms: ['Danio rerio', 'Mus musculus'],
      publication_title: 'Grafting to Zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Preliminary research on Grafting to Zebrafish',
      citation: 'Proffer, Prim. "Grafting to Zebrafish". March 15, 2020.',
      additional_info: 'This tablet was co-authored by Postworth Docktor.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:08+0000',
      updated_at: '2020-08-15T22:01:08+0000'
    },
    {
      id: 9,
      category: 'DATASET',
      title: 'Imported GEO Dataset',
      url: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE31712',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        title: 'Imported Zebrafish Analyis',
        platform: 'Amazon s3 Database',
        technology: 'R-readable array',
        description: 'Data collected from genetically modified zebrafish.',
        accession_code: 'GSE24528',
        number_samples: '15'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: null,
      needs_mta: false,
      needs_irb: false,
      needs_abstract: false,
      imported: true,
      shipping_requirements: null,
      import_source: 'GEO',
      grants: [2],
      organisms: ['Danio rerio'],
      publication_title: 'Data collected from genetically modified zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      citation:
        'Proffer, Prim. "Data collected from genetically modified zebrafish". March 15, 2020.',
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:08+0000',
      updated_at: '2020-08-15T22:01:08+0000'
    },
    {
      id: 10,
      category: 'DATASET',
      title: 'Imported SRA Dataset',
      url: 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE37165',
      organization: 1,
      pubmed_id: '32223680',
      additional_metadata: {
        title: 'GEO Zebrafish Analysis',
        description:
          'This dataset has interesting implications for future research.',
        embargo_date: '2020-01-30',
        number_samples: '15'
      },
      contact_user: '10000000-0f5a-4165-b518-b2386a753d6f',
      sequence_maps: [],
      mta_attachment: null,
      needs_mta: false,
      needs_irb: false,
      needs_abstract: false,
      imported: true,
      shipping_requirements: 1,
      import_source: 'SRA',
      grants: [2],
      organisms: null,
      publication_title: 'Data collected from genetically modified zebrafish',
      pre_print_doi: '10.1109/5.771073',
      pre_print_title: 'Proposal for Data Collection from Zebrafish',
      citation:
        'Proffer, Prim. "Data collected from genetically modified zebrafish". March 15, 2020.',
      additional_info: 'This paper was co-authored by Postworth Docktor.',
      embargo_date: '2020-01-30',
      created_at: '2020-08-15T22:01:08+0000',
      updated_at: '2020-08-15T22:01:08+0000'
    }
  ]
}

export default {
  fakeSearchMaterialsResponse
}
