# Generated by Django 2.2.12 on 2020-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "updated_at",
                "permissions": (
                    ("delete_resources", "delete_resources"),
                    ("add_members", "add_members"),
                    ("manage_permissions", "manage_permissions"),
                    ("add_owner", "add_owner"),
                    ("remove_members", "remove_members"),
                    ("add_resources", "add_resources"),
                    ("edit_resources", "edit_resources"),
                    ("archive_resources", "archive_resources"),
                    ("view_requests", "view_requests"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
        migrations.RemoveField(model_name="material", name="contact_email",),
        migrations.RemoveField(model_name="material", name="contact_name",),
        migrations.RemoveField(model_name="material", name="needs_mta",),
        migrations.AddField(
            model_name="user",
            name="grants",
            field=models.ManyToManyField(
                through="resources_portal.GrantUserAssociation", to="resources_portal.Grant"
            ),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("INVALID", "INVALID"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
