# Generated by Django 2.2.13 on 2020-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address", name="address_line_2", field=models.TextField(null=True),
        ),
    ]
