# Generated by Django 2.2.12 on 2020-06-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="attachment", name="sequence_map_for",),
    ]
