# Generated by Django 2.2.12 on 2020-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.TextField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user", name="published_name", field=models.TextField(null=True),
        ),
    ]
