# Generated by Django 2.2.12 on 2020-05-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "updated_at",
                "permissions": (
                    ("delete_resources", "delete_resources"),
                    ("add_members", "add_members"),
                    ("manage_permissions", "manage_permissions"),
                    ("add_owner", "add_owner"),
                    ("remove_members", "remove_members"),
                    ("add_resources", "add_resources"),
                    ("edit_resources", "edit_resources"),
                    ("archive_resources", "archive_resources"),
                    ("view_requests", "view_requests"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
    ]
