# Generated by Django 2.2.13 on 2020-06-22 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="attachment", options={"get_latest_by": "updated_at"},),
        migrations.AlterField(
            model_name="attachment",
            name="sequence_map_for",
            field=models.ForeignKey(
                default=None,
                help_text="The cell line this seq_map is for. Only valid for seq_map attachments.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequence_maps",
                to="resources_portal.Material",
            ),
        ),
    ]
