# Generated by Django 3.0.3 on 2020-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(through='resources_portal.OrganizationUserAssociation', to='resources_portal.Organization'),
        ),
    ]
