# Generated by Django 2.2.12 on 2020-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationusersetting",
            name="perms_granted_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_requested_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_updated_notif",
            field=models.BooleanField(default=True),
        ),
    ]
