# Generated by Django 2.2.12 on 2020-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="delivered", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="perms_granted_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_requested_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_updated_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("INVALID", "INVALID"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
