# Generated by Django 2.2.12 on 2020-06-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_remove_attachment_sequence_map_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="sequence_map_for",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequence_maps",
                to="resources_portal.Material",
            ),
        ),
    ]
