# Generated by Django 2.2.12 on 2020-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_auto_20200608_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="delivered", field=models.BooleanField(null=True),
        ),
    ]
