# Generated by Django 2.2.13 on 2020-09-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_auto_20200922_1944"),
    ]

    operations = [
        migrations.RemoveField(model_name="materialshareevent", name="time",),
        migrations.AlterField(
            model_name="materialshareevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REQUEST_REJECTED", "REQUEST_REJECTED"),
                    ("REQUEST_CANCELLED", "REQUEST_CANCELLED"),
                    ("REQUEST_ACCEPTED", "REQUEST_ACCEPTED"),
                    ("REQUESTER_IRB_ADDED", "REQUESTER_IRB_ADDED"),
                    ("REQUESER_MTA_ADDED", "REQUESER_MTA_ADDED"),
                    ("REQUESTER_PAYMENT_METHOD_ADDED", "REQUESTER_PAYMENT_METHOD_ADDED"),
                    ("REQUESTER_PAYMENT_NOTES_ADDED", "REQUESTER_PAYMENT_NOTES_ADDED"),
                    ("SHARER_MTA_ADDED", "SHARER_MTA_ADDED"),
                    ("REQUEST_IN_FULFILLMENT", "REQUEST_IN_FULFILLMENT"),
                    ("REQUEST_FULFILLED", "REQUEST_FULFILLED"),
                    ("REQUEST_VERIFIED_FULFILLED", "REQUEST_VERIFIED_FULFILLED"),
                    ("REQUEST_FULFILLMENT_NOTE_ADDED", "REQUEST_FULFILLMENT_NOTE_ADDED"),
                    ("REQUEST_REASSIGNED", "REQUEST_REASSIGNED"),
                    ("REQUEST_ISSUE_OPENED", "REQUEST_ISSUE_OPENED"),
                    ("REQUEST_ISSUE_CLOSED", "REQUEST_ISSUE_CLOSED"),
                    ("MATERIAL_MTA_REQUIREMENTS_CHANGED", "MATERIAL_MTA_REQUIREMENTS_CHANGED"),
                    ("MATERIAL_IRB_REQUIREMENTS_CHANGED", "MATERIAL_IRB_REQUIREMENTS_CHANGED"),
                    (
                        "MATERIAL_SHIPPING_REQUIREMENTS_CHANGED",
                        "MATERIAL_SHIPPING_REQUIREMENTS_CHANGED",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
