# Generated by Django 2.2.12 on 2020-04-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationinvitation", options={"get_latest_by": "updated_at"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("add_resources", "add_resources"),
                    ("add_members_and_manage_permissions", "add_members_and_manage_permissions"),
                    ("approve_requests", "approve_requests"),
                )
            },
        ),
    ]
