# Generated by Django 3.0.3 on 2020-04-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_organizationinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.TextField(help_text="The name of the attachment.", null=True)),
                ("s3_bucket", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_key", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={"db_table": "attachments", "get_latest_by": "created_at",},
        ),
        migrations.AlterModelOptions(
            name="organizationinvitation", options={"get_latest_by": "updated_at"},
        ),
        migrations.RemoveField(model_name="material", name="mta_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="executed_mta_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="irb_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="requester_signed_mta_s3_url",),
        migrations.AddField(
            model_name="material",
            name="mta_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="executed_mta_attachment",
            field=models.ForeignKey(
                help_text="Attachment containing the MTA after it has been signed by all parties.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_executed_mta",
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="irb_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_irb",
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="requester_signed_mta_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_signed_mta",
                to="resources_portal.Attachment",
            ),
        ),
    ]
