# Generated by Django 2.2.13 on 2020-09-25 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_auto_20200922_1944"),
    ]

    operations = [
        migrations.RemoveField(model_name="materialshareevent", name="time",),
        migrations.AddField(
            model_name="materialshareevent",
            name="material_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_events",
                to="resources_portal.MaterialRequest",
            ),
        ),
        migrations.AlterField(
            model_name="materialshareevent",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_share_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="materialshareevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REQUEST_OPENED", "REQUEST_OPENED"),
                    ("REQUEST_REJECTED", "REQUEST_REJECTED"),
                    ("REQUEST_CANCELLED", "REQUEST_CANCELLED"),
                    ("REQUEST_APPROVED", "REQUEST_APPROVED"),
                    ("REQUEST_IN_FULFILLMENT", "REQUEST_IN_FULFILLMENT"),
                    ("REQUEST_FULFILLED", "REQUEST_FULFILLED"),
                    ("REQUEST_VERIFIED_FULFILLED", "REQUEST_VERIFIED_FULFILLED"),
                    ("REQUEST_FULFILLMENT_NOTE_ADDED", "REQUEST_FULFILLMENT_NOTE_ADDED"),
                    ("REQUEST_REASSIGNED", "REQUEST_REASSIGNED"),
                    ("REQUESTER_IRB_ADDED", "REQUESTER_IRB_ADDED"),
                    ("REQUESTER_MTA_ADDED", "REQUESTER_MTA_ADDED"),
                    ("REQUESTER_PAYMENT_METHOD_ADDED", "REQUESTER_PAYMENT_METHOD_ADDED"),
                    (
                        "REQUESTER_PAYMENT_METHOD_NOTES_ADDED",
                        "REQUESTER_PAYMENT_METHOD_NOTES_ADDED",
                    ),
                    ("SHARER_MTA_ADDED", "SHARER_MTA_ADDED"),
                    ("REQUEST_ISSUE_OPENED", "REQUEST_ISSUE_OPENED"),
                    ("REQUEST_ISSUE_CLOSED", "REQUEST_ISSUE_CLOSED"),
                    ("MATERIAL_MTA_REQUIREMENTS_CHANGED", "MATERIAL_MTA_REQUIREMENTS_CHANGED"),
                    ("MATERIAL_IRB_REQUIREMENTS_CHANGED", "MATERIAL_IRB_REQUIREMENTS_CHANGED"),
                    (
                        "MATERIAL_ABSTRACT_REQUIREMENTS_CHANGED",
                        "MATERIAL_ABSTRACT_REQUIREMENTS_CHANGED",
                    ),
                    (
                        "MATERIAL_SHIPPING_REQUIREMENTS_CHANGED",
                        "MATERIAL_SHIPPING_REQUIREMENTS_CHANGED",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
