# Generated by Django 2.2.13 on 2020-06-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_auto_20200612_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.TextField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user", name="published_name", field=models.TextField(null=True),
        ),
    ]
