# Generated by Django 2.2.13 on 2020-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0002_auto_20200612_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="delivered", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="perms_granted_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_requested_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="transfer_updated_notif",
            field=models.BooleanField(default=True),
        ),
    ]
