# Generated by Django 2.2.12 on 2020-04-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0003_auto_20200424_1937"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="mta_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="executed_mta_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="irb_s3_url",),
        migrations.RemoveField(model_name="materialrequest", name="requester_signed_mta_s3_url",),
        migrations.AlterField(
            model_name="material",
            name="embargo_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.TextField(help_text="The name of the attachment.", null=True)),
                ("s3_bucket", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_key", models.CharField(blank=True, max_length=255, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "sequence_map_for",
                    models.ForeignKey(
                        help_text="The cell line this seq_map is for. Only valid for seq_map attachments.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sequence_maps",
                        to="resources_portal.Material",
                    ),
                ),
            ],
            options={"db_table": "attachments", "get_latest_by": "created_at",},
        ),
        migrations.AddField(
            model_name="material",
            name="mta_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mta_materials",
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="executed_mta_attachment",
            field=models.ForeignKey(
                help_text="Attachment containing the MTA after it has been signed by all parties.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_executed_mta",
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="irb_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_irb",
                to="resources_portal.Attachment",
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="requester_signed_mta_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests_signed_mta",
                to="resources_portal.Attachment",
            ),
        ),
    ]
