# Generated by Django 2.2.13 on 2020-10-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0003_auto_20200925_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SHIPPING_CODE", "SHIPPING_CODE"),
                    ("REIMBURSEMENT", "REIMBURSEMENT"),
                    ("OTHER_PAYMENT_METHODS", "OTHER_PAYMENT_METHODS"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
