# Generated by Django 2.2.12 on 2020-04-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0003_auto_20200427_2211"),
    ]

    operations = [
        migrations.AlterModelOptions(name="organization", options={"get_latest_by": "created_at"},),
        migrations.AlterModelOptions(
            name="organizationinvitation",
            options={
                "get_latest_by": "updated_at",
                "permissions": (
                    (
                        "add_members_and_manage_permissions",
                        "Can add members and manage their permissions",
                    ),
                ),
            },
        ),
    ]
