# Generated by Django 2.2.12 on 2020-05-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200501_1518"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "created_at",
                "permissions": (
                    ("add_resources", "add_resources"),
                    ("add_members_and_manage_permissions", "add_members_and_manage_permissions"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="material",
            name="embargo_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
