# Generated by Django 3.0.3 on 2020-04-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200324_1531"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material", old_name="material_type", new_name="category",
        ),
        migrations.AddField(
            model_name="material",
            name="title",
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
    ]
