# Generated by Django 2.2.13 on 2020-10-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20201026_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="import_source",
            field=models.CharField(
                choices=[
                    ("GEO", "GEO"),
                    ("SRA", "SRA"),
                    ("DBGAP", "DBGAP"),
                    ("DATASET", "DATASET"),
                    ("PROTOCOLS_IO", "PROTOCOLS_IO"),
                    ("ADDGENE", "ADDGENE"),
                    ("JACKSON_LABS", "JACKSON_LABS"),
                    ("ATCC", "ATCC"),
                    ("ZIRC", "ZIRC"),
                    ("OTHER", "OTHER"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
