# Generated by Django 2.2.12 on 2020-04-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200429_1749"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "created_at",
                "permissions": (
                    ("add_resources", "add_resources"),
                    ("add_members_and_manage_permissions", "add_members_and_manage_permissions"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
    ]
