# Generated by Django 2.2.12 on 2020-06-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200605_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="sequence_map_for",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequence_maps",
                to="resources_portal.Material",
            ),
        ),
    ]
