# Generated by Django 2.2.12 on 2020-05-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200501_1518"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "updated_at",
                "permissions": (
                    ("add_resources", "add_resources"),
                    ("add_members_and_manage_permissions", "add_members_and_manage_permissions"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ORG_REQUEST_CREATED", "ORG_REQUEST_CREATED"),
                            ("ORG_INVITE_CREATED", "ORG_INVITE_CREATED"),
                            ("ORG_INVITE_ACCEPTED", "ORG_INVITE_ACCEPTED"),
                            ("ORG_REQUEST_ACCEPTED", "ORG_REQUEST_ACCEPTED"),
                            ("ORG_INVITE_REJECTED", "ORG_INVITE_REJECTED"),
                            ("ORG_REQUEST_REJECTED", "ORG_REQUEST_REJECTED"),
                            ("ORG_INVITE_INVALID", "ORG_INVITE_INVALID"),
                            ("ORG_REQUEST_INVALID", "ORG_REQUEST_INVALID"),
                            ("MTA_UPLOADED", "MTA_UPLOADED"),
                            ("APPROVE_REQUESTS_PERM_GRANTED", "APPROVE_REQUESTS_PERM_GRANTED"),
                            ("TRANSFER_REQUESTED", "TRANSFER_REQUESTED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(editable=False)),
                (
                    "associated_material",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources_portal.Material",
                    ),
                ),
                (
                    "associated_organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resources_portal.Organization",
                    ),
                ),
                (
                    "associated_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notified_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "notifications", "get_latest_by": "created_at",},
        ),
    ]
