# Generated by Django 3.0.3 on 2020-04-08 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0004_auto_20200324_1531"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="material_type",),
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.CharField(
                choices=[
                    ("CELL_LINE", "CELL_LINE"),
                    ("PLASMID", "PLASMID"),
                    ("PROTOCOL", "PROTOCOL"),
                    ("DATASET", "DATASET"),
                    ("MODEL_ORGANISM", "MODEL_ORGANISM"),
                    ("PDX", "PDX"),
                    ("OTHER", "OTHER"),
                ],
                default="PLASMID",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="material", name="needs_abstract", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="title",
            field=models.TextField(default="", help_text="The title of the material."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.TextField(default="", help_text="The name of the organization."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="change_in_request_status_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="new_request_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="reminder_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="request_approval_determined_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="request_assigned_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user", name="updated_at", field=models.DateTimeField(auto_now=True),
        ),
    ]
