# Generated by Django 3.0.3 on 2020-04-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "005"),
    ]

    operations = [
        migrations.RemoveField(model_name="material", name="material_type",),
        migrations.AddField(
            model_name="material", name="imported", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="material",
            name="needs_abstract",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="needs_irb",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="needs_mta",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
