# Generated by Django 3.0.3 on 2020-03-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0005_auto_20200323_2022"),
    ]

    operations = [
        migrations.DeleteModel(name="OrganizationUserPermission",),
    ]
