# Generated by Django 2.2.12 on 2020-06-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0005_auto_20200605_2114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="sequence_map_for",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sequence_maps",
                to="resources_portal.Material",
            ),
        ),
    ]
