# Generated by Django 2.2.12 on 2020-05-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0005_auto_20200501_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRequirements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("needs_shipping_address", models.BooleanField(default=False)),
                ("needs_payment", models.BooleanField(default=False)),
                ("accepts_shipping_code", models.BooleanField(default=False)),
                ("accepts_reimbursement", models.BooleanField(default=False)),
                ("accepts_other_payment_methods", models.BooleanField(default=False)),
                ("restrictions", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={"db_table": "shipping_requirements", "get_latest_by": "updated_at",},
        ),
        migrations.RemoveField(model_name="material", name="needs_shipping_info",),
        migrations.AddField(
            model_name="material",
            name="shipping_requirements",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources_portal.ShippingRequirements",
            ),
        ),
    ]
