# Generated by Django 3.0.3 on 2020-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0005_auto_20200401_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.TextField(
                default="New Organization", help_text="The name of the organization."
            ),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="change_in_request_status_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="new_request_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="reminder_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="request_approval_determined_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="request_assigned_notif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.CharField(
                choices=[
                    ("CELL_LINE", "CELL_LINE"),
                    ("PLASMID", "PLASMID"),
                    ("PROTOCOL", "PROTOCOL"),
                    ("DATASET", "DATASET"),
                    ("MOUSE_MODEL", "MOUSE_MODEL"),
                    ("ZEBRAFISH_MODEL", "ZEBRAFISH_MODEL"),
                    ("PDX", "PDX"),
                    ("OTHER", "OTHER"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="title",
            field=models.TextField(default="New Material", help_text="The title of the material."),
        ),
    ]
