# Generated by Django 2.2.13 on 2020-12-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0005_auto_20201027_2129"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialrequest",
            old_name="is_active",
            new_name="is_active_requester",
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="is_active_sharer",
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
