# Generated by Django 3.0.3 on 2020-03-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0006_delete_organizationuserpermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "created_at",
                "permissions": [("approve_requests", "Can approve requests")],
            },
        ),
    ]
