# Generated by Django 2.2.13 on 2020-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0006_auto_20201203_1858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.TextField(null=True),
        ),
    ]
