# Generated by Django 2.2.13 on 2020-07-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0007_auto_20200629_1926"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"get_latest_by": "updated_at", "ordering": ["updated_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="grant", options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="materialrequest",
            options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="materialshareevent",
            options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "get_latest_by": "updated_at",
                "ordering": ["updated_at", "id"],
                "permissions": (
                    ("delete_resources", "delete_resources"),
                    ("add_members", "add_members"),
                    ("manage_permissions", "manage_permissions"),
                    ("add_owner", "add_owner"),
                    ("remove_members", "remove_members"),
                    ("add_resources", "add_resources"),
                    ("edit_resources", "edit_resources"),
                    ("archive_resources", "archive_resources"),
                    ("view_requests", "view_requests"),
                    ("approve_requests", "approve_requests"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="organizationinvitation",
            options={"get_latest_by": "updated_at", "ordering": ["updated_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="organizationusersetting",
            options={"get_latest_by": "created_at", "ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="shippingrequirements",
            options={"get_latest_by": "updated_at", "ordering": ["updated_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="user", options={"get_latest_by": "created_at", "ordering": ["created_at"]},
        ),
    ]
