# Generated by Django 2.2.13 on 2020-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0009_auto_20200707_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="material", name="is_archived", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("MTA", "MTA"),
                    ("SIGNED_MTA", "SIGNED_MTA"),
                    ("EXECUTED_MTA", "EXECUTED_MTA"),
                    ("IRB", "IRB"),
                    ("SIGNED_IRB", "SIGNED_IRB"),
                    ("EXECUTED_IRB", "EXECUTED_IRB"),
                    ("SEQUENCE_MAP", "SEQUENCE_MAP"),
                ],
                max_length=32,
            ),
        ),
    ]
