# Generated by Django 2.2.13 on 2020-07-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0009_auto_20200707_1440"),
    ]

    operations = [
        migrations.RenameField(model_name="material", old_name="organism", new_name="organisms",),
    ]
