# Generated by Django 2.2.13 on 2021-02-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0010_grant_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="text_body",),
    ]
