# Generated by Django 2.2.13 on 2020-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0010_auto_20200723_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="material", name="is_archived", field=models.BooleanField(default=False),
        ),
    ]
