# Generated by Django 2.2.13 on 2020-07-30 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0011_material_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("saved_for_reuse", models.BooleanField(default=False)),
                ("name", models.TextField()),
                ("institution", models.TextField()),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField()),
                ("locality", models.TextField()),
                ("postal_code", models.TextField()),
                ("state", models.TextField()),
                ("country", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "address",
                "ordering": ["created_at", "id"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to="resources_portal.Address",
            ),
        ),
    ]
