# Generated by Django 2.2.13 on 2021-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0011_remove_notification_text_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrequirement",
            name="accepted_payment_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
