# Generated by Django 2.2.13 on 2020-08-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0012_auto_20200730_2039"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="access_token", new_name="orcid_access_token",
        ),
        migrations.RenameField(
            model_name="user", old_name="refresh_token", new_name="orcid_refresh_token",
        ),
    ]
