# Generated by Django 2.2.13 on 2020-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0012_auto_20200730_2039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("INVALID", "INVALID"),
                    ("CANCELLED", "CANCELLED"),
                    ("FULFILLED", "FULFILLED"),
                    ("VERIFIED_FULFILLED", "VERIFIED_FULFILLED"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
