# Generated by Django 2.2.13 on 2020-08-10 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0013_auto_20200806_1417"),
    ]

    operations = [
        migrations.RemoveField(model_name="grant", name="users",),
        migrations.RemoveField(model_name="user", name="grants",),
        migrations.AddField(
            model_name="grant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="resources_portal.Organization",
            ),
        ),
        migrations.DeleteModel(name="GrantUserAssociation",),
    ]
