# Generated by Django 2.2.13 on 2020-08-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0015_auto_20200813_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="has_issues",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("IN_FULFILLMENT", "IN_FULFILLMENT"),
                    ("FULFILLED", "FULFILLED"),
                    ("VERIFIED_FULFILLED", "VERIFIED_FULFILLED"),
                    ("REJECTED", "REJECTED"),
                    ("INVALID", "INVALID"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORG_REQUEST_CREATED", "ORG_REQUEST_CREATED"),
                    ("ORG_INVITE_CREATED", "ORG_INVITE_CREATED"),
                    ("ORG_INVITE_ACCEPTED", "ORG_INVITE_ACCEPTED"),
                    ("ORG_REQUEST_ACCEPTED", "ORG_REQUEST_ACCEPTED"),
                    ("ORG_INVITE_REJECTED", "ORG_INVITE_REJECTED"),
                    ("ORG_REQUEST_REJECTED", "ORG_REQUEST_REJECTED"),
                    ("ORG_INVITE_INVALID", "ORG_INVITE_INVALID"),
                    ("ORG_REQUEST_INVALID", "ORG_REQUEST_INVALID"),
                    ("SIGNED_MTA_UPLOADED", "SIGNED_MTA_UPLOADED"),
                    ("EXECUTED_MTA_UPLOADED", "EXECUTED_MTA_UPLOADED"),
                    ("APPROVE_REQUESTS_PERM_GRANTED", "APPROVE_REQUESTS_PERM_GRANTED"),
                    ("TRANSFER_REQUESTED", "TRANSFER_REQUESTED"),
                    ("TRANSFER_APPROVED", "TRANSFER_APPROVED"),
                    ("TRANSFER_REJECTED", "TRANSFER_REJECTED"),
                    ("TRANSFER_FULFILLED", "TRANSFER_FULFILLED"),
                    ("REMOVED_FROM_ORG", "REMOVED_FROM_ORG"),
                    ("REQUEST_ISSUE_OPENED", "REQUEST_ISSUE_OPENED"),
                    ("REQUEST_ISSUE_CLOSED", "REQUEST_ISSUE_CLOSED"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MaterialRequestIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        default="OPEN",
                        max_length=32,
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="resources_portal.MaterialRequest",
                    ),
                ),
            ],
            options={
                "db_table": "material_request_issues",
                "ordering": ["created_at", "id"],
                "get_latest_by": "created_at",
            },
        ),
    ]
