# Generated by Django 2.2.13 on 2020-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0015_auto_20200813_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user", name="orcid", field=models.TextField(null=True, unique=True),
        ),
    ]
