# Generated by Django 2.2.13 on 2020-08-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0016_auto_20200818_1537"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="access_token", new_name="orcid_access_token",
        ),
        migrations.RenameField(
            model_name="user", old_name="refresh_token", new_name="orcid_refresh_token",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
    ]
