# Generated by Django 2.2.13 on 2020-08-19 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0018_auto_20200819_1655"),
    ]

    operations = [
        migrations.CreateModel(
            name="FulfillmentNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_notes",
                        to="resources_portal.MaterialRequest",
                    ),
                ),
            ],
            options={
                "db_table": "fulfillment_notes",
                "ordering": ["created_at", "id"],
                "get_latest_by": "created_at",
            },
        ),
    ]
