# Generated by Django 2.2.13 on 2020-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0019_fulfillmentnote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationinvitation",
            old_name="request_reciever",
            new_name="request_receiver",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ADDED_TO_ORG", "ADDED_TO_ORG"),
                    ("ORG_REQUEST_CREATED", "ORG_REQUEST_CREATED"),
                    ("ORG_INVITE_CREATED", "ORG_INVITE_CREATED"),
                    ("ORG_INVITE_ACCEPTED", "ORG_INVITE_ACCEPTED"),
                    ("ORG_REQUEST_ACCEPTED", "ORG_REQUEST_ACCEPTED"),
                    ("ORG_INVITE_REJECTED", "ORG_INVITE_REJECTED"),
                    ("ORG_REQUEST_REJECTED", "ORG_REQUEST_REJECTED"),
                    ("ORG_INVITE_INVALID", "ORG_INVITE_INVALID"),
                    ("ORG_REQUEST_INVALID", "ORG_REQUEST_INVALID"),
                    ("SIGNED_MTA_UPLOADED", "SIGNED_MTA_UPLOADED"),
                    ("EXECUTED_MTA_UPLOADED", "EXECUTED_MTA_UPLOADED"),
                    ("APPROVE_REQUESTS_PERM_GRANTED", "APPROVE_REQUESTS_PERM_GRANTED"),
                    ("TRANSFER_REQUESTED", "TRANSFER_REQUESTED"),
                    ("TRANSFER_APPROVED", "TRANSFER_APPROVED"),
                    ("TRANSFER_REJECTED", "TRANSFER_REJECTED"),
                    ("TRANSFER_CANCELLED", "TRANSFER_CANCELLED"),
                    ("TRANSFER_FULFILLED", "TRANSFER_FULFILLED"),
                    ("TRANSFER_VERIFIED_FULFILLED", "TRANSFER_VERIFIED_FULFILLED"),
                    ("REMOVED_FROM_ORG", "REMOVED_FROM_ORG"),
                    ("REQUEST_ISSUE_OPENED", "REQUEST_ISSUE_OPENED"),
                    ("REQUEST_ISSUE_CLOSED", "REQUEST_ISSUE_CLOSED"),
                ],
                max_length=32,
            ),
        ),
    ]
