# Generated by Django 2.2.13 on 2020-08-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0022_rename_shipping_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrequirement",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="resources_portal.Organization",
            ),
        ),
    ]
