# Generated by Django 2.2.13 on 2020-08-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0023_shippingrequirement_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingrequirement",
            name="sharer_pays_shipping",
            field=models.BooleanField(default=False),
        ),
    ]
