# Generated by Django 2.2.13 on 2020-09-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0024_shippingrequirement_sharer_pays_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="requester_abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
