# Generated by Django 2.2.13 on 2020-09-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0025_materialrequest_requester_abstract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="shipping_requirements",
            new_name="shipping_requirement",
        ),
    ]
