# Generated by Django 2.2.13 on 2020-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0026_shipping_requirement_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(default="New description."),
            preserve_default=False,
        ),
    ]
