# Generated by Django 2.2.13 on 2020-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0027_organization_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("SHIPPING_CODE", "SHIPPING_CODE"),
                    ("REIMBURSMENT", "REIMBURSMENT"),
                    ("OTHER_PAYMENT_METHODS", "OTHER_PAYMENT_METHODS"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="payment_method_notes",
            field=models.TextField(null=True),
        ),
    ]
