# Generated by Django 2.2.13 on 2020-09-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0028_auto_20200904_1603"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="message",),
        migrations.RemoveField(
            model_name="organizationusersetting", name="change_in_request_status_notif",
        ),
        migrations.RemoveField(model_name="organizationusersetting", name="misc_notif",),
        migrations.RemoveField(model_name="organizationusersetting", name="new_request_notif",),
        migrations.RemoveField(model_name="organizationusersetting", name="perms_granted_notif",),
        migrations.RemoveField(model_name="organizationusersetting", name="reminder_notif",),
        migrations.RemoveField(
            model_name="organizationusersetting", name="request_approval_determined_notif",
        ),
        migrations.RemoveField(
            model_name="organizationusersetting", name="request_assigned_notif",
        ),
        migrations.RemoveField(
            model_name="organizationusersetting", name="transfer_requested_notif",
        ),
        migrations.RemoveField(
            model_name="organizationusersetting", name="transfer_updated_notif",
        ),
        migrations.AddField(
            model_name="materialrequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="associated_grant",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="resources_portal.Grant"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="associated_material_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources_portal.MaterialRequest",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="associated_material_request_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources_portal.MaterialRequestIssue",
            ),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="non_assigned_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationusersetting",
            name="weekly_digest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_non_assigned_notifs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_weekly_digest",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    (
                        "MATERIAL_REQUEST_SHARER_ASSIGNED_NEW",
                        "MATERIAL_REQUEST_SHARER_ASSIGNED_NEW",
                    ),
                    ("MATERIAL_REQUEST_SHARER_RECEIVED", "MATERIAL_REQUEST_SHARER_RECEIVED"),
                    ("MATERIAL_REQUEST_SHARER_ASSIGNED", "MATERIAL_REQUEST_SHARER_ASSIGNED"),
                    ("MATERIAL_REQUEST_SHARER_ASSIGNMENT", "MATERIAL_REQUEST_SHARER_ASSIGNMENT"),
                    ("MATERIAL_REQUEST_SHARER_APPROVED", "MATERIAL_REQUEST_SHARER_APPROVED"),
                    ("MATERIAL_REQUEST_SHARER_REJECTED", "MATERIAL_REQUEST_SHARER_REJECTED"),
                    ("MATERIAL_REQUEST_SHARER_CANCELLED", "MATERIAL_REQUEST_SHARER_CANCELLED"),
                    (
                        "MATERIAL_REQUEST_SHARER_RECEIVED_INFO",
                        "MATERIAL_REQUEST_SHARER_RECEIVED_INFO",
                    ),
                    (
                        "MATERIAL_REQUEST_SHARER_RECEIVED_MTA",
                        "MATERIAL_REQUEST_SHARER_RECEIVED_MTA",
                    ),
                    (
                        "MATERIAL_REQUEST_SHARER_EXECUTED_MTA",
                        "MATERIAL_REQUEST_SHARER_EXECUTED_MTA",
                    ),
                    (
                        "MATERIAL_REQUEST_SHARER_IN_FULFILLMENT",
                        "MATERIAL_REQUEST_SHARER_IN_FULFILLMENT",
                    ),
                    ("MATERIAL_REQUEST_SHARER_FULFILLED", "MATERIAL_REQUEST_SHARER_FULFILLED"),
                    ("MATERIAL_REQUEST_SHARER_VERIFIED", "MATERIAL_REQUEST_SHARER_VERIFIED"),
                    (
                        "MATERIAL_REQUEST_ISSUE_SHARER_REPORTED",
                        "MATERIAL_REQUEST_ISSUE_SHARER_REPORTED",
                    ),
                    ("MATERIAL_REQUEST_REQUESTER_ACCEPTED", "MATERIAL_REQUEST_REQUESTER_ACCEPTED"),
                    (
                        "MATERIAL_REQUEST_REQUESTER_IN_FULFILLMENT",
                        "MATERIAL_REQUEST_REQUESTER_IN_FULFILLMENT",
                    ),
                    (
                        "MATERIAL_REQUEST_REQUESTER_EXECUTED_MTA",
                        "MATERIAL_REQUEST_REQUESTER_EXECUTED_MTA",
                    ),
                    (
                        "MATERIAL_REQUEST_REQUESTER_FULFILLED",
                        "MATERIAL_REQUEST_REQUESTER_FULFILLED",
                    ),
                    ("MATERIAL_REQUEST_REQUESTER_REJECTED", "MATERIAL_REQUEST_REQUESTER_REJECTED"),
                    (
                        "MATERIAL_REQUEST_REQUESTER_CANCELLED",
                        "MATERIAL_REQUEST_REQUESTER_CANCELLED",
                    ),
                    ("MATERIAL_ADDED", "MATERIAL_ADDED"),
                    ("MATERIAL_ARCHIVED", "MATERIAL_ARCHIVED"),
                    ("MATERIAL_DELETED", "MATERIAL_DELETED"),
                    ("ORGANIZATION_NEW_MEMBER", "ORGANIZATION_NEW_MEMBER"),
                    ("ORGANIZATION_BECAME_OWNER", "ORGANIZATION_BECAME_OWNER"),
                    ("ORGANIZATION_NEW_OWNER", "ORGANIZATION_NEW_OWNER"),
                    ("ORGANIZATION_MEMBER_LEFT", "ORGANIZATION_MEMBER_LEFT"),
                    ("ORGANIZATION_NEW_GRANT", "ORGANIZATION_NEW_GRANT"),
                    ("ORGANIZATION_INVITE", "ORGANIZATION_INVITE"),
                ],
                max_length=64,
            ),
        ),
    ]
