# Generated by Django 2.2.13 on 2020-09-08 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0030_auto_20200909_1608"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification", old_name="associated_grant", new_name="grant",
        ),
        migrations.RenameField(
            model_name="notification", old_name="associated_material", new_name="material",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="associated_material_request",
            new_name="material_request",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="associated_material_request_issue",
            new_name="material_request_issue",
        ),
        migrations.RenameField(
            model_name="notification", old_name="associated_organization", new_name="organization",
        ),
        migrations.RemoveField(model_name="notification", name="delivered",),
        migrations.AddField(
            model_name="notification",
            name="email_delivered",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_delivered_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="viewed_notifications_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="associated_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
