# Generated by Django 2.2.13 on 2020-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources_portal", "0032_auto_20200915_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="weekly_digest_last_sent",
            field=models.DateTimeField(null=True),
        ),
    ]
