name: deploy-client-staging

on: push

jobs:
  deploy-client-staging:
    container: node:lts-buster
    env:
      ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install vercel
        run: yarn global add vercel@19.2.0

      - name: Deploy to Staging
        run: cd client && $(yarn global bin)/vercel --confirm --prod --token $ZEIT_TOKEN --local-config vercel.staging.json --scope ccdl
