name: prod-backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: prod-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load 1Password Secrets
        id: 1password
        uses: 1password/load-steps.1password.outputs-action@v1
        with:
          export-env: false
        env:
          OP_CONNECT_HOST: "${{ secrets.OP_CONNECT_HOST }}"
          OP_CONNECT_TOKEN: "${{ secrets.OP_CONNECT_TOKEN }}"
          DATABASE_PASSWORD: "${{ OP_PRODUCTION_DATABASE_PASSWORD }}"
          DJANGO_SECRET_KEY: "${{ OP_PRODUCTION_DJANGO_SECRET_KEY }}"
          DOCKER_ID: "${{ OP_DOCKER_ID }}"
          DOCKER_PASSWORD: "${{ OP_DOCKER_PASSWORD }}"
          AWS_ACCESS_KEY_ID: "${{ OP_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ OP_AWS_SECRET_ACCESS_KEY }}"
          SSH_PRIVATE_KEY: "${{ OP_SSH_PRIVATE_KEY }}"
          SSH_PUBLIC_KEY: "${{ OP_SSH_PUBLIC_KEY }}"
          OAUTH_URL: "${{ OP_PRODUCTION_OAUTH_URL }}"
          OAUTH_CLIENT_ID: "${{ OP_PRODUCTION_OAUTH_CLIENT_ID }}"
          OAUTH_CLIENT_SECRET: "${{ OP_PRODUCTION_OAUTH_CLIENT_SECRET }}"
          SENTRY_DSN: "${{ OP_SENTRY_DSN }}"


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Deploy
        run: cd infrastructure && python3 deploy.py -e prod -u deployer -d ccdl -v $(git rev-parse HEAD)
        env:
          DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.PROD_DJANGO_SECRET_KEY }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          API_SSH_KEY: ${{ secrets.API_SSH_KEY }}
          OAUTH_URL: ${{ secrets.PROD_OAUTH_URL }}
          OAUTH_CLIENT_ID: ${{ secrets.PROD_OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.PROD_OAUTH_CLIENT_SECRET }}
          SENTRY_IO_URL: ${{ secrets.SENTRY_IO_URL }}
          SENTRY_ENV: prod-api
