name: deploy-client-staging

on:
  push:
    branches:
      - dev

jobs:
  deploy-client-staging:
    container: node:lts-buster
    env:
      ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install now
        run: yarn global add now@19.2.0

      - name: Deploy to Staging
        run: cd client && $(yarn global bin)/now  --confirm --prod --token $ZEIT_TOKEN --local-config now.staging.json --scope ccdl
