name: prod-backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: prod-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load 1Password Secrets
        id: op-load-secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_CONNECT_HOST: "${{ secrets.OP_CONNECT_HOST }}"
          OP_CONNECT_TOKEN: "${{ secrets.OP_CONNECT_TOKEN }}"
          DATABASE_PASSWORD: "${{ secrets.OP_PRODUCTION_DATABASE_PASSWORD }}"
          DJANGO_SECRET_KEY: "${{ secrets.OP_PRODUCTION_DJANGO_SECRET_KEY }}"
          DOCKER_ID: "${{ secrets.OP_DOCKER_ID }}"
          DOCKER_PASSWORD: "${{ secrets.OP_DOCKER_PASSWORD }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.OP_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.OP_AWS_SECRET_ACCESS_KEY }}"
          SSH_PRIVATE_KEY: "${{ secrets.OP_SSH_PRIVATE_KEY }}"
          SSH_PUBLIC_KEY: "${{ secrets.OP_SSH_PUBLIC_KEY }}"
          OAUTH_URL: "${{ secrets.OP_PRODUCTION_OAUTH_URL }}"
          OAUTH_CLIENT_ID: "${{ secrets.OP_PRODUCTION_OAUTH_CLIENT_ID }}"
          OAUTH_CLIENT_SECRET: "${{ secrets.OP_PRODUCTION_OAUTH_CLIENT_SECRET }}"
          SENTRY_DSN: "${{ secrets.OP_SENTRY_DSN }}"


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: Deploy
        run: cd infrastructure && python3 deploy.py -e prod -u deployer -d ccdl -v $(git rev-parse HEAD)
        env:
          DATABASE_PASSWORD: ${{ steps.op-load-secrets.outputs.DATABASE_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ steps.op-load-secrets.outputs.DJANGO_SECRET_KEY }}
          DOCKER_ID: ${{ steps.op-load-secrets.outputs.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ steps.op-load-secrets.outputs.DOCKER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ steps.op-load-secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.op-load-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          SSH_PRIVATE_KEY: ${{ steps.op-load-secrets.outputs.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ steps.op-load-secrets.outputs.SSH_PUBLIC_KEY }}
          OAUTH_URL: ${{ steps.op-load-secrets.outputs.OAUTH_URL }}
          OAUTH_CLIENT_ID: ${{ steps.op-load-secrets.outputs.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ steps.op-load-secrets.outputs.OAUTH_CLIENT_SECRET }}
          SENTRY_DSN: ${{ steps.op-load-secrets.outputs.SENTRY_DSN }}
          SENTRY_ENV: prod-api
