name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build & test dependencies
        run: sudo pip3 install pre-commit==1.21.0
      - name: Run pre-commit hooks on all files
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Build the stack
        run: docker-compose build
      - name: Test
        run: docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py && ./manage.py test"
