name: actions

on: push

jobs:
  # https://github.com/pre-commit/action
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: set PY
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set perms
        run: chmod -R a+rw api
      - name: Build the stack
        run: docker-compose --env-file ./docker-compose.env build
      - name: Test
        run: docker-compose --env-file ./docker-compose.env run --rm api ./run_tests.sh
