name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v1.0.1
      - name: Build the stack
        run: docker-compose build
      - name: Test
        run: docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py && ./manage.py test"
